### ISSUE TITLE
Add advanced options to configure certificate checks

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-desktop#1036]
Since options `imap_certificate_checks` and `smtp_certificate_checks` were added to the Rust core in https://github.com/deltachat/deltachat-core-rust/pull/647 they need to be added to the Desktop client.

Going to try to do it myself.

**Comment by Jikstra** [comment]
You probably need to first add the constants to deltachat-node and update the rust core there. Can help you with this, if you want we can also do an audio/video hack session on this.

**Comment by link2xt** [comment]
I did not any constants to FFI, going to use `0`, `1`, `2` and `3` for now :)

**Comment by r10s** [comment]
cmp question at https://github.com/deltachat/deltachat-ios/issues/322

i think it is important to keep the non-power-users in mind. there are tons of self-signed click-hosters here in germany. so we have to choose the defaults very carefully. 

i think the idea @hpk42 pointed out somewhere else is reasonable: be lazy on default - but if we know due to the provider-database or by other sources (maybe autoconfigure) that the certificatiate should be good, we should check that.

i do not think it is of much worth to check _always_ and scare the users even before they're really onboarded. i think we do not need this additional ux barrier currently.

**Comment by link2xt** [comment]
This setting goes into advanced settings, so users who want certificate checking can select "strict" mode. Default option is `0` which means Automatic. Now it means no certificate checks, but in the future it is going to use provider database and can be improved with TOFU.

**Comment by pabzm** [comment]
This appears to have been implemented, closing it.
