### ISSUE TITLE
Delta Desktop in Windows app store

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#1052]
As to the release efforts -- did you look into what it takes to make Delta chat desktop available on the Windows app store? Some folks, including @nikomatsakis have asked for this, arguing that handling independent installers is annoying and prefering the app store handling.

**Comment by Simon-Laux** [comment]
https://www.electron.build/configuration/win#WindowsConfiguration-target
electronbuilder `target= appx`
https://developer.microsoft.com/en-us/store/register

**Comment by r10s** [comment]
when looking into that: also the macOS App Store would be cool.

i assume we can use the existing merlinux developer account as we're using already for ios.

**Comment by Simon-Laux** [comment]
@r10s I think that's just an file upload away.

**Comment by Simon-Laux** [comment]
though lets make it release ready first before publishing versions...

**Comment by Simon-Laux** [comment]
So microsoft rejected our sumbission last time for the following reasons:

- [ ] We are not part of the Desktop Bridge program yet
- [X] ~~The app crashed before they could test it~~ should be fixed with the newer releases, but we can contact MS if it happens again and ask them for help with troubleshooting.
- [ ] App icons missing (@NeoRon82 created them for us using an genartor for appicons that is included in visual studio https://github.com/deltachat/interface/pull/32, we only still need to **include them in the desktop** repo now)

**Comment by Simon-Laux** [comment]
we now have a working 1.4 preview version on the microsoft store https://www.microsoft.com/en-us/p/deltachat/9pjtxx7hn3pk
