### ISSUE TITLE
subtitle disappears in chatview

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#1130]
The first picture is when i select the dev chat. 
![one](https://user-images.githubusercontent.com/73579/68546242-a4bcad00-03d4-11ea-8e8b-ac8c18b927ab.png)

the second picture is after i typed a few characters into the message input box. 

![two](https://user-images.githubusercontent.com/73579/68546252-b30ac900-03d4-11ea-9101-90a66bb6912c.png)

the "18 members" is gone.

**Comment by Jikstra** [comment]
Yup can reproduce

**Comment by Simon-Laux** [comment]
Its not the css, its that the smaller function to get the chat info is called and I didn't implement the new subtitle function there because that would mean that we need to fetch all contacts and make it slower.
Anyways we can implement https://github.com/deltachat/deltachat-desktop/issues/1129 while fixing this its a similar place in code.
