### ISSUE TITLE
Electron apps must be updated to get into macOS App Store

### ISSUE THREAD

**Issue by duckdalbe** [deltachat/deltachat-desktop#1134]
Currently no electron app can be submitted to the macOS App Store, because Apple tightend the checks: <https://github.com/electron/electron/issues/20027>.

There's a development version of electron available that disables certain features, which passes Apples test, but works slower: <https://github.com/electron/electron/pull/20965>.

AFAIK DC desktop should be available via the macOS App Store, once it's stable. So that issue should be watched.

**Comment by Simon-Laux** [comment]
We're currently on electron 4 because there was an SUID sandbox issue on debian when going above version 4 (https://github.com/deltachat/deltachat-desktop/issues/895) not sure if its already fixed because the upstream electron issue was closed before it was really fixed.

**Comment by Jikstra** [comment]
The suid thing wont get fixed as far as i know. This SUID thing seems to be the default way to do proper sandboxing on unix.

**Comment by Simon-Laux** [comment]
so we need another binary for debian?

**Comment by pabzm** [comment]
Electron versions https://github.com/electron/electron/releases/tag/v5.0.13 and https://github.com/electron/electron/releases/tag/v6.1.7 fix this by including a workaround.

These workarounds may introduce performance regressions according to the electron developers, but many people reported that their apps still run fine with it.

For electron >= 7 there's apparently no fix yet, because the developers [want a "real" solution](https://github.com/electron/electron/issues/20027#issuecomment-565271491) [to the problem](https://github.com/electron/electron/issues/20027#issuecomment-565865582) in those releases.

**Comment by Simon-Laux** [comment]
we upgraded electron to `6.1.7` in #1400
