### ISSUE TITLE
ARM / ARM64 builds for e.g. Ubuntu Touch, RPI

### ISSUE THREAD

**Issue by gsantner** [deltachat/deltachat-desktop#1250]
- Platform (linux/mac/windows): Linux
- Delta Chat Desktop Version: none
- Expected behavior:

I cannot find an ARM or ARM64 build of delta chat. It would be great to be able to have delta chat client also for Rasperry PI and for non-Android/iOS mobile OS like [Ubuntu touch](https://ubuntu-touch.io/)

- Actual behavior: No such builds.
- Steps to reproduce the problem: -
- Screenshots: -
- Logs: -

**Comment by Simon-Laux** [comment]
This is an electron app, as such its **not optimized in anyway to run on a mobile device**, so I wouldn't recommend it. (both **performance** and screen size)
The better way would be to make a mobile client that uses qt or gtk with libhandy.
We have plans for that but right now we're busy with making the existent platforms work nicely so we can get a first stable version that isn't beta or alpha anymore.

There is a start for making a client with qt: https://github.com/deltachat/deltachat-qt

Also you can compile deltachat-core (the library that actually is the main component DeltaChat) for arm, but for the deltachat desktop we would also need to compile arm nodebindings and probably we also need an arm device to do that. - That's currently out of scope for us, especially since this electron app wouldn't run well on mobile devices. Feel free to try it when you want, though.

Also for more general feature requests like an app for mobile gnu+linux our [forum](https://support.delta.chat/) is a better place, because we like to keep our issue tracker mostly bugs and feature request people actually are working on.
loosely related: https://support.delta.chat/t/are-there-any-native-linux-desktop-apps-in-the-works/215

As for mobile linux I would for now recommend the running the android version with https://anbox.io/ if you can run anbox, I don't know its state on mobile to be honest.

**Comment by gsantner** [comment]
notice: I didn't know where to put this hence here. hope to get at least beyond a "wontfix" here : smile : .

**Comment by Simon-Laux** [comment]
I plan to work on a native app, but currently it's really out of scope.
If you have a raspberry you feel free to try getting a arm release. We could add it as an unofficial community build then. :wink:

**Comment by Jikstra** [comment]
Don't know much about Ubuntu Touch, but seems like Anbox runs on it and you can use it to run android apps on ubuntu touch. Probably that's a better way to go?

**Comment by Jikstra** [comment]
Closing this issue as no one of us is going to work on this in the near future and this repo is mainly about the desktop app.

**Comment by ivan-avalos** [comment]
Any updates on this? ARM64 laptops are getting popular, the ARM64 platform is no longer specific to mobile devices or SBCs. Element, for example, works flawlessly on my Pinebook Pro.

**Comment by Jikstra** [comment]
> Any updates on this? ARM64 laptops are getting popular, the ARM64 platform is no longer specific to mobile devices or SBCs. Element, for example, works flawlessly on my Pinebook Pro.

Not really. I'm open to any contribution in this direction, but I don't have a device with which I could try this. But this path is interesting, of course for pinebook pro but also for the mac m1 thingy. I guess we would need to cross compile the rust core and node bindings to arm64, which would need some love over at the deltachat-node repo. It seems like electron builder is adding some headaches for this too: https://www.beekeeperstudio.io/blog/electron-apps-for-arm-and-raspberry-pi.

**Comment by ivan-avalos** [comment]
I'm getting this not-too-useful error:
```
1223 verbose stack Error: deltachat-node@1.50.0 install: `node-gyp-build "npm run build:core" "npm run build:bindings:c:postinstall" && npm run build:bindings:ts `
1223 verbose stack Exit status 1
1223 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
1223 verbose stack     at EventEmitter.emit (node:events:379:20)
1223 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
1223 verbose stack     at ChildProcess.emit (node:events:379:20)
1223 verbose stack     at maybeClose (node:internal/child_process:1065:16)
1223 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:296:5)
1224 verbose pkgid deltachat-node@1.50.0
1225 verbose cwd /home/avalos/Downloads/deltachat-desktop-git/src/deltachat-desktop-git
1226 verbose Linux 5.10.7-1-MANJARO-ARM
1227 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--verbose"
1228 verbose node v15.6.0
1229 verbose npm  v6.14.11
1230 error code ELIFECYCLE
1231 error errno 1
1232 error deltachat-node@1.50.0 install: `node-gyp-build "npm run build:core" "npm run build:bindings:c:postinstall" && npm run build:bindings:ts `
1232 error Exit status 1
1233 error Failed at the deltachat-node@1.50.0 install script.
1233 error This is probably not a problem with npm. There is likely additional logging output above.
1234 verbose exit [ 1, true ]
```

**Comment by Jikstra** [comment]
That's really not helpful :D Can you post the complete output? Sometimes the last 50 lines of the npm output are just complete irrelevant. Another way of doing things would be to first clone deltachat-node.
```
git clone https://github.com/deltachat/deltachat-node.git
npm i
npm run submodule

# And then slowly start building things step by step
# Have a look at the scripts part in package.json, to
# understand the build steps.

# First step would be to build the rust core
npm run build:core:rust

# Then the constants
npm run build:core:constants

# then the c bindingins
npm run build:bindings:c

# some post c bindings stuff
npm run build:bindings:postinstal;

# and finally the ts to js transpilation
npm run build:bindings:ts

# and now you should have node bindings, test if
# they work with
npm test
```
