### ISSUE TITLE
Bug: chatstore is not correctly cleared when account is switched?

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1260]
somehow it tries to open a chat with the id of the chat that was open in the last account.

**Comment by nicodh** [comment]
I don't see that behaviour. What I see is, that each time a chat is selected the SLECT_CHAT action is dispatched twice. The reason is that here https://github.com/deltachat/deltachat-desktop/blob/master/src/renderer/components/message/MessageList.js#L50 an useEffect is triggered on chatId change and fetches the chat again.
I will investigate...

**Comment by Simon-Laux** [comment]
Ok I need to correct/clarify: the chat from the last account is still open after switching accounts

**Comment by nicodh** [comment]
Ok - now I understand and hopefully fixed it.
