### ISSUE TITLE
Show explaination if there are no contact requests

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-desktop#1638]
- Platform (linux/mac/windows):
Windows 8.1 Pro.

- Delta Chat Desktop Version:
1.3.3.

- Expected behavior:
It should not be possible to select "Contact requests" from the global three-dot menu when no contact request exists.

- Actual behavior:
It is possible to select "Contact requests" from the global three-dot menu when no contact request exists.

- Step to reproduce the problem:
-- Click the global three-dot menu when no contact request exists. (The menu item should be disabled.) (I have highlighted the element with a red frame.)

- Screenshot:
![grafik](https://user-images.githubusercontent.com/51095533/81870721-c4e14a80-9576-11ea-8066-06095f02b75e.png)

**Comment by gerryfrancis** [comment]
This issue could be seen as an enhancement, but for now it is not good to see an empty list and a text as follows:

![grafik](https://user-images.githubusercontent.com/51095533/81917080-03a5ed80-95d5-11ea-81f8-e109d604812a.png)

I belive that the average user cannot understand the current behavior.

**Comment by Jikstra** [comment]
Hmm i think it would be enough to show those grey elements in the messagelist with a text around "You don't have any contact requests yet". Hiding a menu item can also be quite confusing, especially when one searches for it because the Faq for example says "Go to Menu -> Contact requests to see.."

**Comment by r10s** [comment]
i agree with @Jikstra, i would not hide or disable it, for the same reasons

but instead, some more explaining would be useful. in fact, we have a string for that, on ios as well as on android we're using `chat_no_contact_requests` (in case `show_emails`!=ALL - otherwise, just use `chat_no_messages` as it is now):

![Screen Shot 2020-05-14 at 16 44 52](https://user-images.githubusercontent.com/9800740/81948825-72e60680-9602-11ea-8280-dcd9e20ea2fe.png)

**Comment by gerryfrancis** [comment]
@Jikstra and @r10s I am with you, that is a good approach, thanks a lot! :+1:
