### ISSUE TITLE
(optional) auto-scaledown picture on send?

### ISSUE THREAD

**Issue by TheOtherDoctor** [deltachat/deltachat-desktop#1681]
- Platform (linux/mac/windows): windows 10
- Delta Chat Desktop Version: 1.2.0
- Expected behavior: submitted picture getting resized (say to screen size) like the android app does.
- Actual behavior: image files are send as-is, resulting in much mailbox space used for possibly less relevant pictures.
- Steps to reproduce the problem:
- Screenshots: -
- Logs: -

I recently realized that the DC android app automatically scales down all highres images to screen size, removing for me the need for the extra step to put ImagePipe inbetween (at least for the resizing); now got surprised that the DC desktop does not do this. 

I'd suggest to add this; and going one step further, it would be nice to have a choice in the send process to scale down or keep original resolution. Depending on use cases, both options have their reason.

As a step zero, I'd think it's worth mentioning these points, where the desktop app behaves differently than the mobile version, in the (built-in) help. As DC desktop installs its own (F1-launchable) help file locally, there might be an opportunity to add such a doc section without much extra work?

**Comment by gerryfrancis** [comment]
@TheOtherDoctor Please try again with with the current Desktop version of Delta Chat, 1.3.4 and report back. Thanks.

**Comment by Simon-Laux** [comment]
No you don't need to test with a new version, its simply not implemented yet.

Please discuss these kind of topics in the Forum instead, we use github issues only for bugs.

I agree that we should mention it in the help, because that missing info can be considered a bug. As the help is just an offline copy of the online FAQ/help of the website and not a desktop specific thing, we should create an issue on the pages repo instead.

I'm looking forward to discuss the steps to implement image/media compression features in our forum. (https://support.delta.chat)

Am 26. Mai 2020 09:57:03 MESZ schrieb gerryfrancis <notifications@github.com>:
>@TheOtherDoctor Please try again with with the current Desktop version
>of Delta Chat, 1.3.4 and report back. Thanks.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/deltachat/deltachat-desktop/issues/1681#issuecomment-633870562

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by r10s** [comment]
there are rough plans to move the rescaling from android to the core, so also desktop and ios will benefit from that (on ios, scaledown is buggy, and we're thinking aboout to get that into core instead of fixing ios, see https://github.com/deltachat/deltachat-ios/issues/733)

ux-wise, i think, it should be dead-simple and default to "rescale" without asking much, many user do not really know or care about that and that would be in-line with android and ios.

also the rescaling affects senders typically more as the receivers. on desktop, typically in a wifi situation, this is even more often the case.

maybe just show a small popup when clicking on the paper clip, as eg. telegram does. attach "file"
would do the same as now, attach "image" would rescale (and can also offer a filter on selection ;)

**Comment by Jikstra** [comment]
Closing as this a core thing :)
