### ISSUE TITLE
create to script to update changelog in appdata.xml

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1697]
A script to update the change-log in `static/chat.delta.desktop.appdata.xml` from `CHANGELOG.md`.

Reason:
We didn't update it in the last releases, because it was too much extra work and only flat-pack uses it AFAIK.
Maybe we can also move the file out of the static folder and find a better place for it? (maybe the build folder or repo root)

**Comment by Simon-Laux** [comment]
@muelli is that file even used by flatpak? does it make sense to generate it from changelog.md?

**Comment by muelli** [comment]
The appdata is used by "store frontends" such as flathub, e.g. https://flathub.org/apps/details/org.gnome.Solanum (just a random app). There you can see the information from the appdata file: https://gitlab.gnome.org/World/Solanum/-/blob/7b5d5b035841a3303e856a1e9c59fde0ee1f2ecc/data/org.gnome.Solanum.appdata.xml.in.in#L31
Other software uses this information, too, e.g. GNOME Software.

Some software exists to automate the maintenance of metainfo files, e.g. https://blog.tenstral.net/2020/03/maintain-release-info-easily-in-metainfo-files.html

**Comment by Simon-Laux** [comment]
I decided to remove the file for now because its super outdated and our flatpak has its own anyway:
https://github.com/flathub/chat.delta.desktop/blob/master/chat.delta.desktop.appdata.xml

**Comment by muelli** [comment]
It's not a Flathub-only thing, though. Although it's close to impossible for any serious distribution to package this app up, Flathub is probably be the only consumer.
Anyway downstream maintenance of this file is probably sub-par. Because it is manual, it adds to the list of pain points when updating the package which in turn reduces chances that more people commit to maintaining the package.
Depending on your release process, you may get inspired by what [Wireshark](https://gitlab.com/wireshark/wireshark/-/blob/master/tools/update-appdata.py) does. Note how they don't bother putting the changelog and how they only carry over the latest release. That's all fair game.
