### ISSUE TITLE
Chat-view does not scroll down on incoming message

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#1783]
current master of node + desktop today. 
![scroll-wrong](https://user-images.githubusercontent.com/73579/87032009-3b4fa100-c1e4-11ea-83b8-b839e5e294a3.png)

This worked with node/desktop-master 1-2 weeks ago.

**Comment by whalehub** [comment]
@hpk42 Isn't this intentional? The [v1.4.2](https://github.com/deltachat/deltachat-desktop/releases/tag/v1.4.2) changelog says
> ### Changed
> - We don't scroll down on incoming messages anymore

**Comment by Simon-Laux** [comment]
@whalehub yes, but this isn't optimal. We still need to work on the chatview to make it nice.

**Comment by MustangDSG** [comment]
I think optimal is: if now a text already scrolled to the bottom, need to auto-scroll on incoming messages, if not, don't need to auto-scroll.

**Comment by r10s** [comment]
https://github.com/deltachat/deltachat-desktop/pull/1742 says, if the view is 7px close to end of list, scrolling down takes place, otherwise not.

maybe, these 7px are the issue and far too less. i would say sth as "height of window" or maybe some static 500px. if in doubt, a bit too much seems to be fine.

scrolling down is only an issue when scrolling up to read the backlog in a frequently used chat - but _then_ it is _really annoying_  and may prevent reading the backlog at all.

**Comment by hpk42** [comment]
i think i found at least one way to reproduce: if i am writing in a chat where the last message is from yesterday, then i will not see my own typed message -- only half of the day-marker.  my own message that ijust type is invisible below

**Comment by Simon-Laux** [comment]
was fixed in #1793
