### ISSUE TITLE
Please provide deltachat-desktop for aarch64

### ISSUE THREAD

**Issue by girlwithnoname** [deltachat/deltachat-desktop#1837]
As a Mobian user (Debian Mobile) I'd like to use deltachat-desktop on Pinephone. This little computer bravely runs even things like nextcloud-desktop and Evolution.

Thus I'd be more than happy if you could provide a build for aarch64 as a debian-package. If you need a tester I'll gladly help. Thanks!

**Comment by Simon-Laux** [comment]
currently the desktop UI is not optimized for mobile. So I would suggest to use the android version instead, it should run in anbox (https://anbox.io/).

There are plans to work on a native mobile app for gnu+linux phones, for that discussion see https://support.delta.chat/t/native-client-for-linux-based-mobile-os/912

**Comment by girlwithnoname** [comment]
Thanks. I don't think the pinephone is performant enough for anbox, so I guess I'll have to wait until a Debian compatible solution exists.

**Comment by Simon-Laux** [comment]
I would try anbox.
Electron, which we use for deltachat desktop, is also not very performance friendly.

**Comment by girlwithnoname** [comment]
Thanks :) Will try it when it becomes available on Mobian.

**Comment by rafael2k** [comment]
I'm using DeltaChat on my Pinephone running Mobian (arm64) and it run fine. Using the flatpak build from:
https://flathub.org/apps/details/chat.delta.desktop

**Comment by n3ph** [comment]
I am running Fedora Asahi Remix on `aarch64`. Would be awesome it packaged for Apple Silicon platforms. 🙏🏼

**Comment by Simon-Laux** [comment]
https://flathub.org/de/apps/chat.delta.desktop has an aarch64 version available, I would recommend using that or coupling yourself for now

**Comment by rafael2k** [comment]
I still pretty much want Debian packaging upstream, just like before with the C version.

**Comment by ell1e** [comment]
Anbox seems like a technical nightmare with it being hard to install and seemingly buggy at least when I tried to use it, needing non-standard kernel modules and apparently causing suspend issues from what I've read, even if it didn't also run badly in terms of performance for those who got it to work at all.

So responsive UI for the Linux version would help a lot. Maybe then one day the mobile code base could even be largely merged with the desktop one?

**Comment by Simon-Laux** [comment]
This test preview build has arm64 builds, though I'll still recommend using the flatpak because of automated and easier updates. We also plan to provide a ppa and other repos for delta chat but we aren't there yet with our limited "man-power", we'd be grateful for help if someone is experienced in that area.

https://download.delta.chat/desktop/v1.45.0-testing-experiment/

Starting with the next release 1.46 and the next test release 1.45 deltachat desktop will also have arm64 builds.
Flatpak already has aarch64 builds today.

**Comment by Simon-Laux** [comment]
> Anbox seems like a technical nightmare

afaik inbox is deprecated and waydroid is the way to go nowadays...

> So responsive UI for the Linux version would help a lot

I agree, but again the core team has limited resources so it is not currently on our roadmap.

> Maybe then one day the mobile code base could even be largely merged with the desktop one?

Unlikely since we use native UI where we can currently (android uses java, iOS uses swift and UIKit, deltatouch uses Qt and lomiri). Though we already share most of the code through our core library (https://github.com/deltachat/deltachat-core-rust), it does all the heavy encryption and email stuff and provides simple apis such as getChatlist and getMessage.

If you are on ubuntu touch you can use deltatouch (https://open-store.io/app/deltatouch.lotharketterer), it's community made by one person in their free time, he wrote a blog post about the process: https://delta.chat/en/2023-07-02-deltatouch.

So if you know someone who knows their way around GTK you could ask them if they want to start making a delta chat client in GTK on top of delta chat core, maybe not even starting from scratch as they could fork some of the matrix clients like fractal (https://gitlab.gnome.org/World/fractal) for its UI.

**Comment by ell1e** [comment]
Waydroid has the same issues, as far as I know. Ubuntu touch isn't really a regular Linux and doesn't seem to be widely adopted for that reason. This does seem to suggest on most Linux phones, deltachat isn't currently usable until this would be in some way addressed.

**Comment by Simon-Laux** [comment]
> If you specifically wanted to avoid the slowness of web/electron UI for phones, 

I personally actually got into app dev with ionic and Cordova, so I'm the wrong person to ask. anyways point is that delta chat core makes it easy to make a new client - also see https://support.delta.chat/t/list-of-all-know-client-projects/3059
