### ISSUE TITLE
Error message is weird on wrong autocrypt setup message key

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#1877]

**Comment by Jikstra** [comment]
@r10s how is it done in the android/ios code? I'm getting back a false from the `continueKeyTransfer` method, but i'm also getting a DC_EVENT_ERROR event, with `[0, "dc_continue_key_transfer: "invalid symmetric key algorithm""]`. Can I just ignore this error event and listen to the false?

**Comment by r10s** [comment]
to know if [dc_continue_key_transfer()](https://c.delta.chat/classdc__context__t.html#a5af2cdd80c7286b2a495d56fa6c0832f) succeeded or not, you have to check the return value.

the DC_EVENT_ERROR-event can be used as pop-up or might be captured or whatever. but the events do not indicate the success or failure of any function.

**Comment by Jikstra** [comment]
@r10s 

> the DC_EVENT_ERROR-event can be used as pop-up or might be captured or whatever. but the events do not indicate the success or failure of any function.

The problem I have is that they have a weird and not-for-normal-users-helpful error message ("invalid symmetric key algorithm")

**Comment by r10s** [comment]
> The problem I have is that they have a weird and not-for-normal-users-helpful error message ("invalid symmetric key algorithm")

ii think, that should be fixed in core then. but as mentioned on irc just now, maybe we should go for some better getting-error-strings.

however, i just had a closer look on the concrete handling in ios/android:

we're displaying `autocrypt_continue_transfer_succeeded` on success and `autocrypt_bad_setup_code` on failure. maybe you should just go for that, at least for now.
