### ISSUE TITLE
deltachat now tries to talk to smtp server with EHLO localhost which is often forbidden

### ISSUE THREAD

**Issue by duritong** [deltachat/deltachat-desktop#1910]
Lots of smtp servers have spam restrictions in place and you need to EHLO using a proper hostname, as spammers are using most often fake hostnames there.

Also things like localhost or so are likely rejected, see https://github.com/Exim/exim/wiki/AclHeloTricks as example.

Just localhost is a pure hostname and not a fqdn.

With the latest release I am now getting the error I gonna attach

This is likely due to: https://github.com/deltachat/deltachat-core-rust/commit/b28f5c871691a0e9fcb405af3407e7e356d54846

**Comment by duritong** [comment]
![2020-10-06-173307_grim cleaned](https://user-images.githubusercontent.com/9511/95225129-baf90600-07fb-11eb-95c0-f7ca052bab84.png)

**Comment by Simon-Laux** [comment]
https://github.com/deltachat/deltachat-core-rust/pull/1908 isn't included in the 1.13.x desktop release it still uses the old 1.45 core.
I will write a hint to the release.

**Comment by duritong** [comment]
Any plans to get that moving? This issue is now present for more than a month and a fix is actually available.

**Comment by Simon-Laux** [comment]
use an older version or use the current master I'd say. Next release will still take 1-3 weeks.
core Situation:
1.46 - fixed it, but had a login bug that the error on configure was non telling what went wrong
1.47 and 1.48 - also fix it, but they add many new features that needed adjustment in the desktop code so we can not just release a new version without testing first because so much changed.

**Comment by duritong** [comment]
Thank you a lot for the update and all the hard work!

**Comment by Simon-Laux** [comment]
1.14.1 is out for downloading on our website, the progress on the release on other platform can be seen on https://github.com/deltachat/deltachat-desktop/issues/2029
