### ISSUE TITLE
hashtags are evil!

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#200]
i like being able to start using desktop, thanks for all the good work!

however, hash tags are evil -- please disable/remove/replace them if possible :) 
![evil-hash](https://user-images.githubusercontent.com/73579/47284603-3c900300-d5e8-11e8-980b-f940ee7b9623.png)

**Comment by r10s** [comment]
iiuc they come from the avatars that have the same background color as the "bubble" in this case so that only the hashtag is left.

however, i also think  that it makes sense to disable them until they are shown in some context (using dc_chat_get_profile_image()/dc_contact_get_profile_image() (the latter is not yet implemented) and/or a colored fallback.

**Comment by r10s** [comment]
great, much, better now :)
