### ISSUE TITLE
Mark messages as read if they are rendered and user actually sees them on screen 

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#214]

**Comment by karissa** [comment]
This could be done at the same time as #6, requesting messages only as needed. 

**sidenote: let's not use p1 labels  (managing labels is annoying and gets outdated quickly)
instead I'd rather use the Projects feature on github which allows us to easily move cards around with the mouse in the same screen instead of managing the labels system across multiple screens.

**Comment by Jikstra** [comment]
> let's not use p1 labels (managing labels is annoying and gets outdated quickly)
instead I'd rather use the Projects feature on github which allows us to easily move cards around with the mouse in the same screen instead of managing the labels system across multiple screens.

Very fine for me :)

> This could be done at the same time as #6, requesting messages only as needed.

Yup. And getting rid of those other preloaded chats maybe too.
