### ISSUE TITLE
The QRCode is not scannable with the dark theme

### ISSUE THREAD

**Issue by Gh0stz0x** [deltachat/deltachat-desktop#2163]
- Operating System (Linux/Mac/Windows/iOS/Android): GNU/Linux Debian 10
- Delta Chat Version: 1.15.2
- Expected behavior: When I have dark mode, I wish I could scan QRCode with my Android smartphone.
- Actual behavior: Currently, it cannot easily scan it.
- Steps to reproduce the problem: Set dark mode, menu -> QR code
- Screenshots: 
![bug](https://user-images.githubusercontent.com/74795149/110042183-af2b5480-7d45-11eb-9e80-14dce2a2f293.png)

I think that in the dark mode, you have to leave white space above and below the QRCode to facilitate the QRCode acquisition.

**Comment by r10s** [comment]
thanks for filing the issue! as already mentioned in DC, i can confirm that this qr-code also does not work on my mogo-g while light-mode works (in general, it is a good idea to surround qr-codes with a significant light border in the color of qr-code light).

also i'd like to repeat here, that inverting qr-codes is no option (even if that would look better :) and should generally not be done. dark areas have to stay dark, light areas have to stay light, otherwise you risk that scanners won't work (and they will not, it is no theory :)
