### ISSUE TITLE
No logfolder or logfile created in Windows (store) version

### ISSUE THREAD

**Issue by havet** [deltachat/deltachat-desktop#2209]
Hi,
wanted to have a look in the logfile because some messages got lost. Couldn't find any logs.

- Operating System (Linux/Mac/Windows/iOS/Android): Windows 10
- Delta Chat Version: 1.15.3
- Expected behavior: logfile/logfolder opened in explorer with: View - Developer - Open the log folder/current logfile
- Actual behavior: Error message: C:\users ... DeltaChat/logs is not accessible ...
- Steps to reproduce the problem: Se expected behavior
- Screenshots: see below
![Error](https://user-images.githubusercontent.com/7511145/113723462-aa194680-96f1-11eb-8adc-5bc0dd184ea0.jpg)

- Logs: NO.

**Comment by Simon-Laux** [comment]
Maybe the windows store version saves its files somewhere else? we should investigate this further

**Comment by havet** [comment]
I've looked in various places, but have not found anything related to Delta Chat. Maybe you'll have to look in the code? I haven't so far.

**Comment by Simon-Laux** [comment]
Looking for in deltachat code would be a waste of time, because its not in it - we get the directories from https://www.npmjs.com/package/application-config#config-location, so maybe its somewhere in there or just some kind of appx-sandboxing applies by windows:
My thinking was that the windows store version might use some sandboxing and stores the apps files in a separate location - in that case we need to adjust the logic in our code that the button also works correctly in the windows store version.

**Comment by Simon-Laux** [comment]
so appx does include additional sandboxing: https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-behind-the-scenes
but I couldn't find where it saves the appdata files to on that docpage other than that it is a `private per-user, per-app location`

**Comment by Simon-Laux** [comment]
found them: `C:\Users\XXXXXX\AppData\Local\Packages\merlinux.DeltaChat_v2ry5hvxhdhyy\LocalCache\Local\DeltaChat\logs`

looks like we need an if statement to change the path when on the windows store version.

**Comment by Simon-Laux** [comment]
Just found out that this also affects opening blob files: they cannot be found, because the application opening them is not in the sandbox Deltachat is in (with being an appx/uwp)
HTML emails work, because they are copies in a temporary directory first.

But this particular issue will probably disappear once core moves the blobfiles to the db, because then we have to copy those files to temporary directories anyway.

CC @r10s @link2xt @hpk42

**Comment by Simon-Laux** [comment]
so in the new version it works, but only if deltachat was not installed before not via the store.
