### ISSUE TITLE
Unknown contact appeared in contact list

### ISSUE THREAD

**Issue by havet** [deltachat/deltachat-desktop#2214]
- Operating System (Linux/Mac/Windows/iOS/Android): Windows 10
- Delta Chat Version: 1.15.3
- Expected behavior: No unknown e-mail addresses in the contact list
- Actual behavior: At the top an apparent spam-address appeared
- Steps to reproduce the problem: normal usage

I intended to start a new chat, clicked New Chat and found the unknown address at the top of the contact list.
I looked into contact request, but the list was empty.
I couldn't remove it, so I chose to start a new chat with the address - just to be able to block it. Then it disappeared from the list.

I cannot figure out how the unknown address was put on the list. DeltaChat must have taken an initiative on it's own. But how? And why? This behaviour must be stopped.

**Comment by Hocuri** [comment]
When starting a new chat, Delta Chat suggests:
- all addresses you wrote an email to. Since the last version, it also suggests recipients in emails that were sent before DC was installed, if the email is still in your "Sent" folder.
- if you grant access to your address book, then all email addresses from your address book
- if you already know Alice and Alice writes an email to you and Bob, then DC also suggests Bob
- contacts you manually created
- people whose QR code you scanned or vice-versa.

Maybe one of these is the case?

**Comment by havet** [comment]
Yes, indeed. I once in the past actually sent a mail to that "suspicious" address. Good to know how Delta Chat collects addresses.
