### ISSUE TITLE
[Discussion] Don't quoute on double click?

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#2226]
Double click is normally selecting a word, so it conflicts with the "double click to quote feature". I suggest putting double click to quote behind an optional setting or removing it completely.

What are your opinions?

CC @Jikstra @nicodh @link2xt @Hocuri @hpk42 @r10s

**Comment by link2xt** [comment]
I don't support having more configuration options, it's harder to maintain, harder to test all the interactions between options, harder to have options in sync between devices etc.

I think I never used double click to quote in DC, always select Reply in the menu. I'm ok with just removing this "double click to quote", but maybe we need a small button somewhere within the bubble or outside to replace it for when right-clicking is inconvenient (touchpads and similar devices)? I think you did some experimental code/mockups for this.

**Comment by Simon-Laux** [comment]
> I think you did some experimental code/mockups for this.

I did but @Jikstra didn't liked it and pushed the double click thing instead. I agreed at the time, because I didn't have a strong opinion on it.

**Comment by Hocuri** [comment]
I'd be in favor of removing "double-click-to-quote", but putting an icon for quoting in the top right corner (Discord and Slack let these icons only appear when you hover your mouse over the message, but I don't mind, they could also just be always there)

**Comment by Hocuri** [comment]
> I don't support having more configuration options, it's harder to maintain, harder to test all the interactions between options, harder to have options in sync between devices etc.

+1

**Comment by r10s** [comment]
+1 for not adding configuration options; we should definitely not do that for this kind of things.

for the double-click: it also conflicts with messages containing an image/video/etc., it confused me several times, enlarging an image where i want to answer (seems i was very used to double click).

so, maybe the double-click is comfortable, but if you are used to that, it stands in the way of many other things. and you have to learn an alternative anyway.

so, even when not doing other things, just relying on the context menu for replies is probably better ux.

up to some point, we had this "button appearing on hovering messages", tbh, i did no like that implementation too much, the button was  too big and added too much noise, too much flickering (i know, telegram does it that way).  
iirc, we had the rough idea to use this button-appears-on-hover, but tuned down, showing the button inside the bubble, maybe bottom-left-aligned (where always is some space because of the date/on the right) or top-right where @Hocuri suggested (there is no space in one-to-ones, so that might be trickier, also i find that less logical, but well) - maybe these are the mockups @link2xt talked about? there were at least some screenshot somewhere.

**Comment by Simon-Laux** [comment]
I would not add buttons, they are difficult to align right, if there are problems on touch screens we could define that long press is equal to right click.

**Comment by r10s** [comment]
> I would not add buttons, they are difficult to align right (with all types of messages)

what about adding the left of the delivery/date area - as that area is present for all messages, that should be easier to add generically. if would still showing them on hover-only, however. sth. like that:

![Screen Shot 2021-04-18 at 21 06 00](https://user-images.githubusercontent.com/9800740/115157861-c0c58300-a08b-11eb-94ad-cf4a95614e7a.png)

but as a first step, only relying on context menu is probably also okay.

> if there are problems on touch screens we could define that long press is equal to right click.

i did not use much touch-screens on desktop yet, but i would expect that this is solved somehow by the os, a quick search also points in that direction: https://answers.microsoft.com/en-us/education_ms/forum/edu_win10-edu_ink/right-click-in-windows-10-using-touch-screen/1de53031-c561-4110-a85d-d60e5edbbbb8 - so maybe, this point is nothing to worry about much.

**Comment by Simon-Laux** [comment]
> as that area is present for all messages anyway

two examples where additional styling would be needed: stickers, images/videos

**Comment by r10s** [comment]
> two examples where additional styling would be needed: stickers, images/videos

don't they have date/delivery currently? so just using the same font/colors/etc. sounds doable with not too much effort, if one wants to go that way. however, of course, i do not know about javascript/node pitfalls that are maybe there, it was just a suggestion, how things _could_ be easier :)

> telegram on mac, telegram on linux doesn't have any buttons on messages at all, only right-click

some have them, some do not :) otoh signal and most email programs have dedicated reply/forward buttons. having email-compat in mind, reply/forward  may become more important for us as well at some point.

however, as said, context-menu-only is okay for now. and maybe everyone is just satisfied with that :)

**Comment by Jikstra** [comment]
> up to some point, we had this "button appearing on hovering messages", tbh, i did no like that implementation too much, the button was too big and added too much noise, too much flickering (i know, telegram does it that way).

+1 I don't like flickering things on hover.


I'm fine with removing double click to reply.

**Comment by Simon-Laux** [comment]
So the conclusion is that we remove the double click to reply functionality.
