### ISSUE TITLE
"Archived chats (n)" not translated

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#224]
![screenshot from 2018-10-26 11-48-00](https://user-images.githubusercontent.com/308049/47559152-0f5b9180-d915-11e8-95eb-8a5b1cd0096c.png)

**Comment by r10s** [comment]
the string comes from deltachat-core, to translate this, node would need to handle DC_EVENT_GET_STRING which is complicated due to the needed return value (the evenqueue/poll fallback we've used in other places may be too time consuming here).

may make sense to give all strings to napi from js-land so that the c-wrapper can answer  DC_EVENT_GET_STRING independently from js then.
more complicated is DC_EVENT_GET_QUANTITY_STRING, however, i think we can get rid of this, it's only used for the subtitle "1 member", "2 members" and so on.

**Comment by ralphtheninja** [comment]
I think for now, I'll just hack it. Parse out the number and translate it after it comes out. But the correct way is obviously to make sure core can deliver it already translated.

**Comment by r10s** [comment]
> But the correct way is obviously to make sure core can deliver it already translated.

yes - and it's not only this string. it's also summaries, subtitles, errors and so on.

**Comment by ralphtheninja** [comment]
> on startup, all strings could be set using:

Sounds great!

**Comment by ralphtheninja** [comment]
Hmm, do the `DC_STR_NOMESSAGES` etc exist already or would they have to be created?
