### ISSUE TITLE
OK button misleading when adding new member to a group that is not yet in contacts

### ISSUE THREAD

**Issue by flipsimon** [deltachat/deltachat-desktop#2565]
In the dialog to add a new member to a group you can type in an email adress. To add the member you have to create a new contact before. If you directly hit the OK button, nothing happens, so the OK button should not be clickable in this moment.

**Comment by hpk42** [comment]
On Mon, Feb 21, 2022 at 17:25 -0800, flipsimon wrote:
> In the dialog to add a new member to a group you can type in an email adress. To add the member you have to create a new contact before. If you directly hit the OK button, nothing happens, so the OK button should not be clickable in this moment.

would it make sense to implicitely add this member rather than disabling the ok button? I've actually found myself several times in this situation and then had to cancel the group-creation, create the contact, and then restart the whole group creation process. If you created and selected 8 members only to notice you want to add a 9th one but it is not a contact yet that's quite annoying.

**Comment by Jikstra** [comment]
> actually found myself several times in this situation and then had to cancel the group-creation, create the contact, and then restart the whole group creation process. 


You can add non contacts to groups by now, but you have to click on the "Add contact" thing.
My idea would be to just show the checkbox on the right as with all other contacts.

![Screenshot_20220222_214031](https://user-images.githubusercontent.com/34889164/155215640-dd5455af-a9dc-46c0-b217-4f4612ba7f62.png)
