### ISSUE TITLE
missing vertical space between webxdc start-button and message-text

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2762]
between the webxdc-start-button  and the messages text, there should be some vertical spacing.

i suggest to use the same amount of space as between webxdc-name/-summary and webxdc-start-button; however, the additional space must not be applied if there is _no_ messages-text, in this case, things are already fine.

<img width="272" alt="Screen Shot 2022-05-17 at 18 44 08" src="https://user-images.githubusercontent.com/9800740/168865236-75c627db-4ced-4d06-8076-400c3e9146b6.png">
red: there is some space missing

&nbsp;
as a side-effect, this may also fix the floating of big emojis into the button as reported in some other channel:
![image_2022-05-17_02-16-02](https://user-images.githubusercontent.com/9800740/168867308-e901bd40-3185-4036-9a4b-c07a5aecdc45.png)
this is a cool-looking bug, btw :)

**Comment by gcamach0** [comment]
Hi @r10s, im looking to make my first open source contribution and i was wondering if there's no one else working on this if I could give it a try

**Comment by r10s** [comment]
hi @gcamach0, first of all: welcome aboard!

i do not think, someone is working on that just now, so, it would be great if you can give it a try!

**Comment by gcamach0** [comment]
Hey guys! I just added a pr #2783 for this issue. I would really appreciate it if you could take a look at it. I will keep an eye out for any comment you may have.
I also saw that a check failed because I didn't update the changelog. I was wondering if it is something that I have to do at once or should I wait to see what results from the review?
