### ISSUE TITLE
Setup-Code von "Autocrypt-Setup-Nachricht senden" aus K-9 Mail wird in DeltaChat nicht akzeptiert

### ISSUE THREAD

**Issue by notYetLost** [deltachat/deltachat-desktop#2805]
1. In OpenKeyChain vorkandenen Schlüssel durch K-9 Mails Autocrypt-Unterstützung via  "Autocrypt-Setup-Nachricht senden" in DeltaChat zu verwenden, schlägt fehl:  der von K-9 Mail angezeigte Setup-Code wird in DeltaChat nicht akzeptiert.

2. In Thunderbird erzeugte geheime Schlüssel lassen sich nur mit Passwortschutz in eine Datei sichern. Zwar lässt sich diese Datei in OpenKeyChain importieren, aber auch der Setup-Code dieses Schlüssels wird nach K-9 Mail "Autocrypt-Setup-Nachricht senden" in DeltaChat nicht akzeptiert

Gibt es eine Lösung, wie für einen Schlüssel der sowohl in Thunderbird, OpenKeyChain/K-9 Mail, und DeltaChat benutzt werden kann?

**Comment by gerryfrancis** [comment]
This is a place to report and fix issues in the Delta Chat source code. For general support in German please visit the German Delta Chat forum at https://support.delta.chat/c/de/12
Thank you for your understanding! :)

**Comment by ecxod** [comment]
It is a huge issue that you do not use openkeychain. Here is the english translation:

1) Using keys pre-created in OpenKeyChain by K-9 Mails autocrypt support via "Send autocrypt setup message" in DeltaChat fails: the setup code displayed by K-9 Mail is not accepted in DeltaChat.
2) Secret keys generated in Thunderbird can only be saved to a file with password protection. Although this file can be imported in OpenKeyChain, but also the setup code of this key is not accepted in DeltaChat after K-9 Mail "Send autocrypt setup message".
Is there a solution how for a key that can be used in both Thunderbird, OpenKeyChain/K-9 Mail, and DeltaChat?
autocrypt is not something you are allowed to model as you like.

**Comment by gerryfrancis** [comment]
@ecxod I am sorry, this is not the appropriate place to argue. Let's discuss about these and other topics in the Delta Chat forum: https://support.delta.chat/
Thank you! :)

**Comment by Simon-Laux** [comment]
So when autocrypt setup does not work that is a bug that should be reported in the core repo https://github.com/deltachat/deltachat-core-rust

For feature requests/proposals such as using openkeychain, please discuss this in our forum as @gerryfrancis mentioned. also openkeychain and k9mail are both on android, so it does not make sense to open an issue on the desktop repo anyway.

**Comment by gerryfrancis** [comment]
The problem in regard to Autocrypt most likely is with K-9 Mail: https://github.com/thundernest/k-9/issues/4867

Their current issue, as far as I understood, is that emails that are sent to self do not contain `prefer-encrypt=mutual` in the Autocrypt header. However, Delta Chat seems to depend on that information, as explained here: https://github.com/deltachat/deltachat-core-rust/blob/f0249096119ad56c2f3751560dc9341f904956c9/src/peerstate.rs#L323-L341

I installed the latest build (version 6.511) of K-9 Mail from F-Droid, and I tried to sync the client with Delta Chat, which failed, too. Then, after reading this and that about how Delta Chat and K-9 Mail handle Autocrypt, I enabled to force mutual mode in K-9 for all emails. Unfortunately `prefer-encrypt=mutual` seems to be included in the Autocrypt header only for emails that are not sent to my own address, because it is missing when I email myself (sender's address = recipient's address).

As the Autocrypt setup message is sent to the own address, but lacks the `mutual` Autocrypt encryption value in the header, this might be the cause why it does not work. Therefore I believe that as soon as the issue which I have mentioned before is solved in K-9 Mail, it might play nicely with Delta Chat, too. Someone may open a new issue in the Delta Chat core repository to officially document, of course, but I think there is not much we can do at the moment.
