### ISSUE TITLE
[Discussion] Pull requests and reviews

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#286]
I think it should be enough with _one_ person reviewing a PR and maybe also leave a PR hanging for max 24 hours, depending on how complex it is. If it's something trivial or urgent, e.g. bug fix that has to be released asap, it's a different matter.

I think we should come to some sort of agreement on this, because right now we want to have rather high velocity but still with reviews and if everyone is to review everything, it doesn't scale and pull requests will be hanging for days, which is bad.

If one person has reviewed and 24 hours has passed with no extra comments, the PR should be merged. If you have comments on a particular PR after this, make a new PR with the changes, or make changes and push directly to master if it's something trivial, or if you don't have time, make an issue and point to the PR that should be adjusted.

**Comment by karissa** [comment]
I agree and disagree at the same time. Since we don't have comprehensive tests (or integration tests) something that seems 'trival' could break the app. I don't think it's bad to wait up to 48 hours for a PR unless it's a very urgent bug fix but then still, I've found that these super fast bug fixes can often break other things..

**Comment by ralphtheninja** [comment]
I hear you. My only concern is that we get pull requests piled up. Maybe we should focus more on tests as well. And 48 hours is fine too.
