### ISSUE TITLE
chat title of some empty chats shown as an error

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#2961]
some empty chats are displayed as follows in 1.33.0:

![Screenshot 2022-10-19 at 22 45 08](https://user-images.githubusercontent.com/9800740/196801126-37ade018-0e75-4182-9c31-e34195c22dcf.png)

for whatever reason, the chat is empty and a chat request.

i can archive pin the chat, so it seem to exist.

delta chat 1.32.1 displays the chat title normally, for the same database.

**Comment by Simon-Laux** [comment]
I have seen this too, I suspect there is a bug in core or the jsonrpc layer.

**Comment by Simon-Laux** [comment]
> delta chat 1.32.1 displays the chat title normally, for the same database.

but for whatever reason the chat is not selectable/clickable

**Comment by Simon-Laux** [comment]
Ok in my case the contact is missing, and so it can't get the Chat, this is a core issue, there is no contact name, so the summary generation failed.

**Comment by Simon-Laux** [comment]
closing it here as missing contacts for contact requests (aka. completely broken chats that you can't even open because of the missing contact -> from_id 0 in the db, no entry for the mentioned email address in the contacts table) is a core problem and there are no actionable items for desktop.

@r10s if your chats are not broken because of missing contacts or are not completely broken (you can still click on them), then please reopen this issue
