### ISSUE TITLE
Title in the account list screen is not fully displayed in German.

### ISSUE THREAD

**Issue by Raiden-GH** [deltachat/deltachat-desktop#2963]
When _DC-Desktop 1.33_ is running in German, the title “_Bekannte E-Mail-Konten_” is not fully displayed in the start screen.

![Startbildschirm Fehler](https://user-images.githubusercontent.com/108235546/197238431-d87da243-d3de-4476-b629-71ffa45f825d.jpeg)

One could make the "_Alle(s) synchronisieren_" button smaller, or just omit the word "_Bekannte_" in the title since the accounts are known anyway. Or of course both.

![Startbildschirm Korrektur](https://user-images.githubusercontent.com/108235546/197238702-533ca595-744a-478c-b18e-ec194dd744d7.jpeg)

**Comment by farooqkz** [comment]
@Simon-Laux What solution do you think is the best here without sacrificing UX?

I have tried making the switch label font size smaller based on text length but it makes it look bad:

![image](https://github.com/deltachat/deltachat-desktop/assets/15038218/6469b4ea-313a-4936-b153-9de0fce3176e)

**Comment by Simon-Laux** [comment]
maybe we could instead find or make an icon that represents it somewhat and then use `title` html attribute to show a tooltip that says "alle synchronisieren"/"sync all" but also, under a new line, a small text explanation of what the button does, so it is clear even to all people.

I this is enabled all Accounts are connected and update in the background, if disabled only the selected account will update.

In the future we want to make it possible to individually enable/disable syncing (in core it's called start_io and stop_io) per account. Currently this ich hacked into desktop UI code, would be better if all that would happen in the core account manager. It's planned, but not started yet.

**Comment by r10s** [comment]
the title should read just "Accounts" or "Switch Accounts" instead of "Known Accounts". "known" does not add any information to the user here, it is clear that the accounts are "known". otherwise we could prepend "known" virtually everywhere :)

this may make the title already a bit shorter, but probably does not solve the issue fully, esp. as there are languages where the "Sync all" string is even longer ...

however, instead of inventing an icon plus tooltip plus additional explanation, i suggest to move the whole switch below the account list. this also makes sense as the option is not that important that it needs to be shown topmost (the default is just fine for most users):

<img width=320 src=https://github.com/deltachat/deltachat-desktop/assets/9800740/41edb84f-b26e-4d0d-a8c9-3bcafc090a3c>
