### ISSUE TITLE
Bundled Emojis fail to load

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#3128]
On windows we have missing emojis:
<img width=300px src=https://user-images.githubusercontent.com/18725968/220350393-3938ad15-0e15-4783-aba6-708b60c0c5fd.png />

And on other systems we have missing flags:

<img width=300px src=https://support.delta.chat/uploads/default/original/2X/e/eccf522f0334cb4e5271cb968c12106ad5bda029.png />

https://support.delta.chat/t/help-testing-the-upcoming-1-34-3-release/2418/8

I suspect somehow the bundles google Noto color emoji font fails to load.

**Comment by Yoandy85** [comment]
the emoji stop loading after a few days of installation
![2023-06-08_183716](https://github.com/deltachat/deltachat-desktop/assets/135717414/d43fa486-b32e-42a8-9557-71d06e0d2ef4)

**Comment by Simon-Laux** [comment]
> after a few days of installation

that sounds super weird... what system/os and deltachat version do you use? from where did you got it? anything special about your system? any other info that could help to reproduce the issue?

**Comment by Simon-Laux** [comment]
ping @Yoandy85

**Comment by YoandyCV** [comment]
Sorry for the delay but I was not available for a long time, that was with version 1.36.1 and it happened both in window 10 pro and in window 8, apparently everything was resolved because with the new versions it has not happened anymore, in these At the moment I am with the test 1.28.0 and it is going great, if I would like to have the option to establish the delta as the default mail application because with the bot the links do not work and it is very uncomfortable, but it is offtopic here
