### ISSUE TITLE
Microsoft Store says "available in 1 language", "English (United States)"

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-desktop#3197]
- Operating System (Linux/Mac/Windows/iOS/Android):
Windows 8.1/10.

- Delta Chat Version:
1.36.x (to date).

- Expected behavior:
The Windows app in Microsoft Store is advertised to be available in several languages.

- Actual behavior:
The Windows app in Microsoft Store is advertised to be available in just one language, "English (United States)".

- Steps to reproduce the problem:
-- Go to Microsoft Store and search for DeltaChat.

- Screenshots:
![grafik](https://user-images.githubusercontent.com/51095533/233116601-1100fa4b-2a8b-485f-9d22-1ae357eb9964.png)

- Logs:
N/A.

**Comment by gerryfrancis** [comment]
@Simon-Laux No, just tested, the store page localization has nothing to do with it, the only language currently available for Delta Chat is "English (United States)".

**Comment by Simon-Laux** [comment]
so turns out it was a property in the electron builder config file, but I needed to go through all codes manually to make sure that they are on the list of supported languages for the store https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/supported-languages?pivots=store-installer-msix
