### ISSUE TITLE
a  group member can remove the group creator -- it makes the group function unuseful

### ISSUE THREAD

**Issue by michael8908** [deltachat/deltachat-desktop#3219]
- Operating System (Linux/Mac/Windows/iOS/Android):
  Windows/Android

- Delta Chat Version:
  Version 1.36.4 (git: v1.33.0-205-g6d91754e)

- Expected behavior
   It should be allowed that a  group member wants to remove the group creator 

- Actual behavior:
  a  group member can remove the group creator -- it makes the group function unuseful

- Steps to reproduce the problem:
- Screenshots:
- Logs:

**Comment by Simon-Laux** [comment]
This is the expected behaviour, there are no group permissions. If your use case requires it because you work with people that can not behave then I recommend using mailing lists.
You can also take part in discussing possible different group types in our forum: https://support.delta.chat/t/new-feature-group-types/263, but as deltachat does not have a centralised server, that can be a source of truth about who is and who isn't in a group, implementing reliable distributed group permissions is very hard or even impossible technically, so I'd really recommend the mailing list approach for now.
Let's move the discussion to the forum, this issue tracker is only for desktop bug and task tracking.
