### ISSUE TITLE
App picture on Flathub is wrong

### ISSUE THREAD

**Issue by maymage** [deltachat/deltachat-desktop#3225]
Hi all, 

sad to say, but the app does not look like the pic on flathub: the (old style) menubar is missing. 

Best

**Comment by maymage** [comment]
Menu bar is this thing here 

![image](https://github.com/deltachat/deltachat-desktop/assets/36572014/b6458cc4-3379-40a1-936b-a490bf5574e3)

**Comment by Simon-Laux** [comment]
also its actually a screenshot from macOS if you look closely xD

**Comment by maymage** [comment]
Hey, wait, does that mean, macOS gets the nice, clean look and on Linux we're stuck with the old style menu bar?

**Comment by Simon-Laux** [comment]
More like the menu bar is integrated into the system top bar like the old ubuntu unity desktop did

**Comment by maymage** [comment]
But the menu bar is not necessary for Delta Chat to function properly in view of the macOS situation, right?

If so, can it be removed or made toggable (hit <Alt>) like on Firefox?

**Comment by Simon-Laux** [comment]
I guess you are unfamiliar with macOS, menu bars are on top of the screen there, so they exist and are visible. DeltaChat currently still needs the menu bar because not all functions are accessible with out it. Changing the language for example. An option to hide was already discussed previously, but currently there are more urgent thing to do. If you want you can try to make a pr for that, If it woks good enough I might merge it, but note that in firefox everything is also available in the hamburger menu AFAIK.

**Comment by maymage** [comment]
> I guess you are unfamiliar with macOS

And with windows too :D

>  If you want you can try to make a pr for that, If it works good enough I might merge it, but note that in firefox everything is also available in the hamburger menu AFAIK.

I'm afraid, that's beyond my capabilities. However it's no good to do away with/hide the menu bar, as long as it holds settings missing otherwise.

**Comment by Simon-Laux** [comment]
https://github.com/flathub/chat.delta.desktop/pull/134 will bring new screenshots, this is also tracked by https://github.com/flathub/chat.delta.desktop/issues/112, so closing here
