### ISSUE TITLE
superfluous information shown in "Saved Messages" profile

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3231]
the following information are not useful but clutter UI:

- "Last Seen" should be hidden - it is always "Unknown", but even showing the last message sent or so does not make sense as the affected person is just seeing themselve in person when accessing the profile :) just hide that option, we just did that on ios cmp. https://github.com/deltachat/deltachat-ios/pull/1881 , android was never showing "Last Seen" for "Saved Messages"

- "Shared Chats" does not make sense as well - these are more or less all chats, so this is basically a copy of the main chatlist. "Shared Chats" for "Saved Messages" are hidden on ios/android as well.

<img width=300 src=https://github.com/deltachat/deltachat-desktop/assets/9800740/1fa7612f-7905-47c3-9dff-f04f2f09198a>

**Comment by Simon-Laux** [comment]
Isn't the whole view profile dialog useless for the self contact?

**Comment by r10s** [comment]
hm, indeed there are not many information left and "gallery" etc is not part of the profile as on android/ios. otoh,  it may be confusing and look like a bug when you cannot tap on the avatar or chat name for some chats, maybe still okay for being removed, not sure

**Comment by Simon-Laux** [comment]
<img width="398" alt="Bildschirmfoto 2023-05-22 um 15 26 38" src="https://github.com/deltachat/deltachat-desktop/assets/18725968/080d8bb1-4c1b-4b57-8692-014abae9ddf2">

could also be an option... but honestly I'd just make it non clickable like telegram because clicking on the self contact and then getting a profile about "saved messages" is a bit confusing...
