### ISSUE TITLE
Verified 1:1 chats are shown with verified-icon inconsistently

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#3320]
with current core-master desktop shows verified icons for some but not all 1:1 chats in the chatlist and message-list title -- but all of the chats have a verified-icon in the contacts profile.  I think desktop should consistently show verified icons in chatlist and message-list title if it shows them in the contact profile as verified.  On Android this works but not sure if @hocuri had to do anything special.

**Comment by Simon-Laux** [comment]
This just means the chats are not protected yet, chat can be unprotected while the contact is verified.
We work with state from an old core version, maybe this state will not be produced anymore with the upcoming core version, but the old state is still there.

**Comment by Hocuri** [comment]
Across all core versions, the correct behavior is that the verified icon is shown on a 1:1 chat exactly if `chat.is_protected()` returns `true`. When exactly the verified icon is shown in the profile hasn't been debated yet.

>  I think desktop should consistently show verified icons in chatlist and message-list title if it shows them in the contact profile as verified.

A contact can be verified, but write from a new key[^1], or write unencrypted. Or maybe they just didn't write you at all since you updated Core. In these cases a contact is verified but the 1:1 chat is not protected. Maybe it's one of these cases?

FTR:
- Android had a bug for some time that it also showed the verified icon on 1:1 chats if `contact.is_verified()` returned `true` (i.e. it showed the verified icon too often)
- Android's current behavior is: _If a 1:1 chat exists_, then a verified icon is shown in the profile title bar if the 1:1 chat is protected. _Otherwise_, a verified icon is shown in the profile title bar if the contact is verified. I do like this behavior, though it does have downsides: Now, there can be a discrepancy between whether a verified icon is shown in a list of contacts and whether it's shown in the profile.

[^1]: That's a case where we still need to talk about, you @hpk42 also brought up a problem with this case lately. But that's unrelated to this issue here.

**Comment by Simon-Laux** [comment]
androids behaviour does not really apply here as the profile/chat view in desktop is a separate dialog, that does not share the navbar/headerbar like android does.
In general we should change the icon, so chat protection and contact verification (2 different things) don't have the same icon.
closing this as it is a discussion and there is no actionable item currently
