### ISSUE TITLE
mailto link inside webxdc causes blank page

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#3355]
![image](https://github.com/deltachat/deltachat-desktop/assets/24558636/75472064-27e7-4672-92e9-d25c9d504c44)

**Comment by Simon-Laux** [comment]
we would need to upgrade electron for this or get rid of the iframe (FILL 500 hack)

**Comment by Simon-Laux** [comment]
this requires electron 25+

**Comment by Simon-Laux** [comment]
https://github.com/deltachat/deltachat-desktop/pull/3381

**Comment by WofWca** [comment]
> get rid of the iframe (FILL 500 hack)

How would that work? I see that the wrapper is still used in #3381.

It looks to me like this piece of code does nothing, after the introduction of the WebRTC exfiltration mitigation:

https://github.com/deltachat/deltachat-desktop/blob/853b584251a5dacf60ebc616f7fb10edffb5c5e5/src/main/index.ts#L247-L264

Because all navigation is prevented anyway:

https://github.com/deltachat/deltachat-desktop/blob/f5f073a8f6c98082cb131bc8eef774c5edaadc7d/src/main/deltachat/webxdc.ts#L367-L370

I might be wrong though.

**Comment by Simon-Laux** [comment]
We need to either get rid of the frame again or use an electron version that has the "will-frame-navigate" event.

Someone could also attempt to backport the event to electron 22, but that might be to complicated.

**Comment by WofWca** [comment]
How does `"will-frame-navigate"` help?

We want an `<iframe>` because:
- Upon initial load, we want to execute the 500 hack before the app gets a chance to execute its code
- If there is a page reload, we need to make sure to have 500 `RTCPeerConnection` at all times while the user script is active.

Does the new Electron allow to solve the reload problem?

**Comment by Simon-Laux** [comment]
> How does "will-frame-navigate" help?

It allows us to use the code you mentioned in your previous comment again.

**Comment by WofWca** [comment]
Yeah, for "will-frame-navigate" that's true (I think), but I'm asking about how it's gonna help get rid of the wrapper `<iframe>`.

**Comment by Simon-Laux** [comment]
It won't, I said we "either" need one or the other, not both.

**Comment by WofWca** [comment]
Oh I see.
How does the new Electron version allow to get rid of the 500 hack then?

**Comment by Simon-Laux** [comment]
>  How does the new Electron version allow to get rid of the 500 hack then?

no, this is just about the `mailto:` stuff discussed in this issue.

My communication seems lacks here, please tell me how to improve it.

**Comment by WofWca** [comment]
Ok, it's my bad, sorry 🤦‍♀️
I read

> we would need to upgrade electron for this or get rid of the iframe (FILL 500 hack)

as "for this _to_ get rid". I thought you have an idea of how to get rid of the `<iframe>`, it's why I keep asking.

**Comment by Simon-Laux** [comment]
looks like we did not even need the electron upgrade, in the end it was `contents.setWindowOpenHandler()`
