### ISSUE TITLE
When creating contacts when creating a new group they are not shown until the group was created.

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#3363]
Steps to reproduce:

1. open create chat dialog
2. create new group
3. add members
4. type in email address for a contact you don't have yet and add it
5. click ok and observe that the contact is not shown in the member list
6. create the group and look open the group profile, observe that the contact now was created an is shown.

Solutions:

A. create the contact directly and don't do these pseudo contacts that get removed again at all.
B. create contact but remove it when group creation is canceled also see #3008
C. show the pseudo contacts in the member list of the group (in the create group dialog)

**Comment by farooqkz** [comment]
I have traced the bug to https://github.com/deltachat/deltachat-desktop/blob/master/src/renderer/components/dialogs/CreateChat.tsx#L662

It turns out when `AddMemberInnerDialog` create a new contact [here](https://github.com/deltachat/deltachat-desktop/blob/master/src/renderer/components/dialogs/CreateChat.tsx#L116), the `searchContacts` does not get updated unless you completely re-mount the `CreateGroupInner` dialog.
