### ISSUE TITLE
composer / draft-area not getting focus after click in command

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#3493]
if I click a command, the draft is set to the command, then I press the shortcut to send message, instead of sending, I get asked if I want to replace current draft, it seems the "send message shortcut" is actually triggering the action of clicking the command again, that is: the command I just clicked has the focus, and hitting enter is triggering click

WARNING: to reproduce you have to have empty composer/draft, if you already have a draft, after clicking a command you get asked to replace current draft and then the composer is focused **BUT** focus is at the beginning not at the end of the text 

- Operating System (Linux/Mac/Windows/iOS/Android): Linux
- Delta Chat Version: 1.40.3

**Comment by Simon-Laux** [comment]
Your description is weird and hard to understand:

### First Bug:

Expected:
after clicking  `/BotCommandSuggestion` the composer should be focused again (at the end of text) so that the shortcut for sending (cmd/ctrl+enter) works

Actual:
after clicking  `/BotCommandSuggestion` the composer has lost focus and the shortcut for sending clicks the bot command suggestion again which is somehow invisibly focused instead.

### Second Bug:

Replacing draft focuses the composer again, but cusor is at start of text, where it should be at the end of the text.

**Comment by Simon-Laux** [comment]
probably same draft loading race as in #3495 could cause this.
