### ISSUE TITLE
replace-draft dialog is buggy and disturbing

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#3494]
when you click a command or a mailto link, you get asked with a disturbing dialog if you want to replace current draft, it happens often when clicking a mailto link in a HTML email that this dialog for some bug gets triggered several times, you have to dismiss it several times, and in general it is too disturbing the user's workflow, instead just don't show a dialog at all, but directly set the new draft, after setting the new draft, user should be able to use ctrl+z / menu item "undo" to undo the changes and recover the old draft if needed

**Comment by Simon-Laux** [comment]
is this on current master?
And I strongly disagree with removing the dialog.
many users don't even know that undo exists and even if that could technically somehow be possible it would break when switching chats. And it will be more complicated coding wise than a simple confirm dialog.

**Comment by adbenitez** [comment]
the dialog almost destroy the whole point in usability of clicking commands, in that case is almost the same than selecting the text and pressing ctrl+c then ctl+v, user can remove draft in many ways, and the undo is easy to discover in menu or common sense when editing text in PC it is common to be able to undo

**Comment by adbenitez** [comment]
> is this on current master?

Version 1.40.3 (git: v1.33.0-314-gcae95205)
but it has been like that since older versions

**Comment by adbenitez** [comment]
as an example, in Android we don't ask for confirmation to replace draft, there user doesn't even have undo shortcut

**Comment by adbenitez** [comment]
same for sharing, it replace existing draft without so much questions

**Comment by Simon-Laux** [comment]
> as an example, in Android we don't ask for confirmation to replace draft, there user doesn't even have undo shortcut

I think that is bad, replacing users data/work without asking for confirmation is horrible.

**Comment by Simon-Laux** [comment]
Also I don't like how you write your issues, I don't want to have to interpret and guess what you mean.

**Comment by Simon-Laux** [comment]
The multiple triggering of uri links / qrcode content was is fixed already since 1.40.4.

I (as a user) would appreciate if you would add a replace confirmation dialog also on android (and iOS).

If you want to discuss its existence further we can **do that in the forum.**
But your arguments thus far were not convincing at all to be honest, so please discuss this in a serious manner and not just "dialogs are annoying", while I argue that loosing a long draft you wrote is even more annoying.

There could be some improvements in the logic, such as checking if the draft is already the thing you clicked, then no replace or dialog is needed.
