### ISSUE TITLE
Text Screen Shots are Over-Compressed

### ISSUE THREAD

**Issue by Copyrites** [deltachat/deltachat-desktop#3591]
- Operating System: Linux
- Delta Chat Version: 1.42.2
- Expected behavior: Readable Text 
- Actual behavior: Fuzzy Text
- Steps to reproduce the problem:
- Set "Outgoing Media Quality" to "balanced"
- Take Screenshot of Text, paste into delta
- Screenshots:
- Logs:

The new automatic compression for images is too high.   I send a lot of text screen shots in Delta and the automatic image compression is making them difficult to read — fuzzying up small text.  Ideally delta should be able to detect if an image has a lot of text and then just do lossless compression.   But in the meantime can we get a setting for "Outgoing Media Quality" to only do lossless compression?

**Comment by r10s** [comment]
for the majority of users it is better to compress than to go for uncompressed; having a screenshot from a phone using several mb or so is unexpected - even apple uses lossy compression for screenshots eg. if you edit it.

we can, of course, consider to adapt the "Balanced" compression, do you have concrete suggestions for that? best, please note them in [forum](https://support.delta.chat), with example images

a global "Media Quality / Lossless", would do more harm than help for overall UX if "just so enabled" as the receiver's bandwidth the sender cannot know about would be wasted.

if you really want to bypass compression, you can already now [send images as file](file https://delta.chat/en/help#does-delta-chat-support-images-videos-and-other-attachments). 

there are several ideas how to improve that option already in the forum, eg. https://support.delta.chat/t/more-convenient-option-to-attach-image-from-gallery-as-original/2761 (for ios, however, that's the same here), i suggest to continue all discussion in the forum, so that the discussion stays visible and to close this issue here (we do not track feature proposals in the issue tracker)

**Comment by Copyrites** [comment]
Ok, I opened a topic in response here:

https://support.delta.chat/t/overcompression-bug/2848
