### ISSUE TITLE
do not enable experimental feature by default

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3684]
“Sync All Accounts In Background” resp. its disabling became an experimental feature, which is okay in general.

however,  experimental features should not be enabled by default.

the other way round, disabling all experimental features should result in sth. as “standard state”.

so, as the option as such should stay experimental, it needs to be be sth. as ~~“Only Sync Foreground Account”~~ “Only Sync Selected Account” (tooltip could read "Synced when selected" then)

EDIT: the following is offtopic and not part of the issue: ~~nb: also the “Power Icon” shown on  the account icons is a bit weird. what about showing a question mark intead? this would also make it clearer to the user what the impact of the option is:  
_not knowing if there is sth. new_  
(a “?” is shown where otherwise a counter appears)~~

**Comment by Simon-Laux** [comment]
> “Only Sync Selected Account” (tooltip could read "Synced when selected" then)

That wording is not clear enough to me what it does. But I agree that the experimental settings should be off by default.

About the power button, for me the question mark is more confusing, as it to me it feels like that delta chat has a bug or fault and thus can not find out how many new messages exist.
The grey power button might not be ideal and a different disconnected icon could be better, but I don't agree with the question mark. also note that the icon will only appear on accounts that you specifically disabled background sync on in the future.

Other programs also use a power icon to symbolise that sth is turned off:

![](https://www.virtualbox.org/manual/images/virtualbox-main.png)

**Comment by Simon-Laux** [comment]
> so, as the option as such should stay experimental

only as long as it is not implemented via core, I plan that for the next release after 1.44, so 1.46. It is not complicated just a bit of code in the account manager and removing code that starts/stops io from desktop ui code.

as soon as it is implemented by core we won't need the setting anymore, we can think about:
- A. whether migrate existing users of that setting, by disabling all accounts
- B. or we can just remove the setting, leaving all accounts enabled by default
- C. B, but send a device message with a screenshot of the context menu on the account where it can be deactivated for background.

nb: An Option to put it offline completely could also be interesting for accounts of deleted email addresses so you can keep it as archive without spamming the log with can not connect messages, but maybe this could also be solved by a smarter connectivity algorithm that stops on 100 failed attempts until you start it again manually in the settings?

Would be better to make multiple issues, one for wording of the option and one for the icon and one for naming.

**Comment by Simon-Laux** [comment]
about the icon, maybe a snowflake or sth similar could also be an idea.

**Comment by Simon-Laux** [comment]
@raiden-social what about the unread message counter?

**Comment by r10s** [comment]
to be clear: icon etc. was just a remark (which i should have left out :) 

the real issue we have is that an experimental must not be enabled by default. if after enabling things are, well, experimental and rough, that okay.

**Comment by Simon-Laux** [comment]
> what would be your suggestion?

Don't really know, I'd currently prefer to postpone deciding on the strings and address it in the next version unless someone has a bright idea for the wording.

I'm working on a core pr to move the logic for this to the account manager in core and make it per account.

I think we the option will stay in advanced settings, maybe go to imap folder settings and would be called sth like "Only connect to account when it is selected", "Disable Background fetch for account", "Disable Background Sync for Account" and the text in the hover message would be telling the user where they can disable it. so no context menu entry, just in advanced settings.

Why no context menu entry? because my recent non-representative poll on mastodon showed that some people want this and others don't want to see it, so just have the option in advanced settings seems to be the solution.

For other platforms the feature can also be useful as it also disables background fetching for the account, so you can keep an account that does not work anymore or that you only want to check manually for "digital detox" or other reasons.

**Comment by r10s** [comment]
> Don't really know

then let's go with the suggestion from above for 1.44 and call if a day, all other thoughts can be done relaxed later.

the wording is not most important.

most important is to keep the ux pattern of "experiments"  for 1.44: for that, we must not mix states, so the the user does not know whats "normal" and whats "experimental"
