### ISSUE TITLE
Adding a reaction makes the chat "scroll up" (then you have to scroll to see new messages)

### ISSUE THREAD

**Issue by WofWca** [deltachat/deltachat-desktop#3753]
- Operating System (Linux/Mac/Windows/iOS/Android): Windows, Linux
- Delta Chat Version: 1.44.0, 828f472a433a56bd77c25cb6f2aebcc556828b36
- Expected behavior: The scroll position remains at the very bottom of the chat
- Actual behavior: The chat becomes "scrolled up", gets "unlocked" from the bottom position
- Steps to reproduce the problem:
  1. Open a chat with someone, scroll to bottom
  2. Let them add a reaction, or add one yourself
  3. Wait for a new message to arrive
- Screenshots:

  https://github.com/deltachat/deltachat-desktop/assets/39462442/1f0adec3-6b10-4e21-a529-a5e522b199e6

- Logs: [none]

I think there should be a proper "declarative" fix. For example, I have noticed that in Chromium if you scroll to the bottom of the page and then increase the height of an element that is somewhere above, out of view, then the scroll height of the page will change, but the scroll position will remain at the bottom, unlike if the element was in view.

Update: oh lord oh please don't tell me this has to be fixed through scroll locking

https://github.com/deltachat/deltachat-desktop/blob/0380993ba6f65f7d52ef2acbb64a3779f9ebca22/src/renderer/stores/messagelist.ts#L309-L310

**Comment by WofWca** [comment]
I'm noticing that our code is very similar to Signal, and Signal doesn't have this issue.

**Comment by Jikstra** [comment]
You can debug it by adding a `display: none;` to `.styles_module_reactions`

**Comment by WofWca** [comment]
> EDIT: Adding margin-bottom: -1px; to .styles_module_reactions fixes it i think. Why this happens? Not so sure...

Hmm idk. Didn't work for me

**Comment by WofWca** [comment]
What did work is this one simple trick (scientists hate me):

https://github.com/signalapp/Signal-Desktop/blob/29c404266863491a3b26a73b24602d36d7a3ac46/stylesheets/_modules.scss#L5573-L5587

Basically we gotta put `overflow-anchor: none;` on all of the messages except the one we want to stay in place (which in this case would be the last message).

**Comment by WofWca** [comment]
I left some extra ideas in #4012. Another quite simple one I have is to have an `IntersectionObserver` set "visible" class on all the visible messages, and ensure that only the last visible one has `overflow-anchor: auto`.
Or we could apply this only to the last message - if it is in view, then turn off anchoring for all the messages. Otherwise have default anchoring.

**Comment by r10s** [comment]
just some thoughts as i was queried:

how is the state "keep scroll down" detected?

iirc, there is somethings as "if the scroll position is not more than _X pixels_ from the bottom, and a new message arrives, scroll down - otherwise the user has scrolled up manually and we stay to not disturb the user reading"

if now the added reactions enlarges the view by more than _X pixels_, the calculation may fail. so, making sure, the threshold is large enough may already help. or, maybe better, recalculate.

**Comment by WofWca** [comment]
Would anybody be against simply adjusting CSS such that reactions are more terse and don't cause height to change?
Until we figure out a better approach.

**Comment by WofWca** [comment]
OK, `display: flex; flex-direction: column-reverse;` on `#message-list` really looks promising. It solves nearly all scrolling problems, including #3763.

But for some reason when more messages are fetched, the scroll position jumps god knows where. However, I think this is not a problem with the approach, but something with our code. We really have a ton of scroll-related code, I'm trying to pinpoint what causes this.
An important thing I found is that the scroll position doesn't jump if I

```javascript
window.fetchMoreTop = fetchMoreTop
window.fetchMoreBottom = fetchMoreBottom
```

And then call those functions manually from the console. The messages get loaded both above and below just fine, and the scroll position is preserved just fine.

**Comment by WofWca** [comment]
@Amzd I think you implemented the "flip message list upside down" on iOS, similarly to my comment above?

**Comment by Amzd** [comment]
Yep on iOS we apply a transform which mirrors along 2 axis the scroll view and then again all the cells and any content we show inside of the scroll view to return those to original. This works because by default a scroll view anchors to the top on iOS. It's a bit of a hassle and I am planning to undo this whenever I have more time. The performance impact of this method is higher than I'd prefer. 

I can't speak for the viability of this on web as I don't know the alternatives.
