### ISSUE TITLE
The account management sidebar does not follow colour scheme

### ISSUE THREAD

**Issue by farooqkz** [deltachat/deltachat-desktop#3794]
It's always dark regardless of the current theme.

Edit: Can reproduce on `1.44.1 (git: v1.33.0-669-gc878fc787)`

**Comment by Simon-Laux** [comment]
this is intentional as long as we think about making accounts separately theme-able. so we'd need to decide on wether we still want to do that or not

**Comment by Simon-Laux** [comment]
<img width="107" alt="Bildschirmfoto 2024-10-03 um 00 07 45" src="https://github.com/user-attachments/assets/d8edbb34-6c92-4663-a75d-8c47b38dc9e1">
<img width="107" alt="Bildschirmfoto 2024-10-03 um 00 09 21" src="https://github.com/user-attachments/assets/3840c7a6-08b0-41b0-aa95-596d20078ddc">

On macOS this might be challenging, because the traffic lights are invisible in the light theme when the system has the dark theme.
Also might make sense to add theming for sidebar with a single light/dark toggle. If we decide each account can have it's own theme then the sidebar is unaffected.

**Comment by Simon-Laux** [comment]
Anyways I'll close this here and reference it instead in the meta issue about the account sidebar

**Comment by r10s** [comment]
> Also might make sense to add theming for sidebar with a single light/dark toggle

solving the issue by addding another option, so we have themes for sidebar and non-sidebar seems over the top.

it is really okay in the  current state, esp compared to other things; i totally agree with closing this issue
