### ISSUE TITLE
Three dots become inactive when opening tabs to the right from Audio

### ISSUE THREAD

**Issue by kermoshina** [deltachat/deltachat-desktop#3865]
- Operating System: Linux
- Delta Chat Version: 1.45
- Actual behavior: When opening tabs to the right from Audio (e.g. Audio, Files, Apps) the three-dot menu becomes inactive (see cursor on the screenshot)
![deltachat-2024-05-26-114804](https://github.com/deltachat/deltachat-desktop/assets/16879492/1134af27-02e2-4833-b0a5-be791f948518)

**Comment by Simon-Laux** [comment]
It becomes inactive because there are no options for those tabs

**Comment by r10s** [comment]
some thoughts: 

ftr, this issue is an successor of https://github.com/deltachat/deltachat-desktop/issues/3523 - and indeed disabling is questionable - as it is never enabled for these tabs.

before the "grid" option was introduced, _always_ the chat menu was shown at this position, which seems to be a good thing, to have this consistent and static. i even think, this is the larger ux issue than the disabled menu ("where is my chat menu where i can archive the chat"?)

question is, what to do with the "grid" option then.

. we could add that to the existing menu. maybe okay.
- or add another button at the place where also other content-related controls (as "search" or "data") are shown

could look as the following. however, not sure, i am not suggesting anything atm, just brainstorming :) 

<img width="766" alt="Screenshot 2024-05-26 at 18 04 37" src="https://github.com/deltachat/deltachat-desktop/assets/9800740/7efdb4b8-839f-4156-8e99-e8baf29d8e18">

which icon does comparable apps are using for that?

however, all in all that seems to be a minor that can be discussed post-1.46 (the issue is not new)
