### ISSUE TITLE
three-dot menu disabled in chat view of audio, files, or apps

### ISSUE THREAD

**Issue by dkg** [deltachat/deltachat-desktop#3987]
- OS: Debian stable (12.5) amd64
- Delta Chat Version: 1.46.1 (installed via .deb)

in a per-chat view, click on the media icon.  from the sub-tabs, choose either "Audio", "Files", or "Apps".  with any of those sub-tabs selected, the three-dot menu (⋮) in the upper right is disabled.  with the other sub-tabs ("Images" or "Video") the three-dot menu (⋮)  is _not_ disabled.

If there's no action choices to take there, just hide the three-dot menu.  making it disabled makes me wonder what i need to do to enable it.

**Comment by r10s** [comment]
yeah, the three-dot menu  should better be hidden, this was also suggested at https://github.com/deltachat/deltachat-desktop/issues/3523 [^1], maybe for technical reason it was disabled only.

however, when hidden, it should be hidden in a way that no shifting of layout elements happens.

[^1]: [#3523](#3523)  is about not showing "Aspect Ratio Grid" on tabs where it does not have effect.  
in general, this issue was introduced with the addition of the  "Aspect Ratio Grid" option for galleries - before, the three-dot-menu was always (so also in gallery) the "Chat Menu" with "Clear Chat", "Archive", "Delete Chat" etc.  
"Aspect Ratio Grid" made the three dot menu context-sensitive then - i am not sure about that change, but might be okay. at least i do not know about complains ppl wondering where "delete chat" is :)

**Comment by Simon-Laux** [comment]
> however, when hidden, it should be hidden in a way that no shifting of layout elements happens.

that's the important part, probably easy by just setting opacity to `0`?
