### ISSUE TITLE
message view not always updated

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3991]
the message view is not always updated; at least not after "clear" in a reproducible way, not sure about other situations.

to reproduce:

- chose "Clear Chat" from the three-dot-menu in the upper right corner
- send a message to that chat from another device (without doing anything on the cleared chat)

-> the message appears in the chatlist, but the chat stays empty.

dc 1.46.1 on mac

https://github.com/deltachat/deltachat-desktop/assets/9800740/908bf7bd-ac1d-48a4-b78d-00f8f99f3af2

**Comment by WofWca** [comment]
I cannot reproduce...
Tried on b8ba8978a61e89670e3127ace4c42f8edef64c08, 1.46.1 (git: v1.33.0-881-g 899f196d)
Also tried muting the chat, as in https://github.com/deltachat/deltachat-desktop/pull/3994#issuecomment-2226296834


https://github.com/user-attachments/assets/2ffec3f6-4ace-42b4-a8f6-0d3ad0152e40

However, if I get a message from the other party (instead of sending one from myself from another device), the message doesn't appear.

https://github.com/user-attachments/assets/12565375-cdcc-4182-8087-1e508ad24817

**Comment by WofWca** [comment]
As Simon pointed out https://github.com/deltachat/deltachat-desktop/pull/4037#issuecomment-2241772875, the issue that I'm describing is the same as your describing.
So, I retract the "cannot reproduce" comment.
