### ISSUE TITLE
Use a proper icon library rather than using individual images

### ISSUE THREAD

**Issue by farooqkz** [deltachat/deltachat-desktop#4174]
Currently we are using few tens of icons, currently living in https://github.com/deltachat/deltachat-desktop/tree/main/images. I think it is a better fit to use some icon node library like FontAwesome or Material Icons or any other choice. These are just examples to convey my meaning of "icon node library" as I don't know the real phrase. There are several benefits:

 - It will give us a nice and ergonomic way to import them.
 - It is easier to credit them. Like later we could use a Software BOM to credit every single library we are using plus their licencing and authors. Now the only way is manually crediting them.
 - It is easier to find out where does the icon come from. Right now they are only images with no reference of origin.
 - It will be harder to mess up with things this way(the icon library way)
 - It is easier to track changes with git or any other SVM as they work with text not image.
 - I think it will also be easier for bundlers like webpack or parcel to optimize them? In the case of parcel, it can already optimize images.

**Comment by Simon-Laux** [comment]
we won't use parcel nor webpack again. Atleast I'm against that.

we get icons from google's material icons. Sometimes we modify some or make our own, but that's relatively rare.

> It is easier to credit them

> It is easier to find out where does the icon come from. Right now they are only images with no reference of origin.

should be documented in `images/licenses`. But no one did that **so I agree that it would be easier to import the non custom icons from an npm package** with an automated way to include only the used images in a release.


How about this:

We add `@material-design-icons/svg`[^1] then use it to import svg files  with `esbuild`s file loader [^2] (copy them to output dir, instead of including them).
We can modify our existing icon component to support it or make a new material icon component.
Then we replace all icons that we didn't modify to use the material icons from the library.
So the old <Icon> component would only be for custom icons.

[^1]: https://www.npmjs.com/package/@material-design-icons/svg#usage, https://marella.me/material-design-icons/demo/svg/
[^2]: https://esbuild.github.io/content-types/#file

**Comment by maxphilippov** [comment]
> we won't use parcel nor webpack again. Atleast I'm against that.
> 
> we get icons from google's material icons. Sometimes we modify some or make our own, but that's relatively rare.
> 
> > It is easier to credit them
> 
> > It is easier to find out where does the icon come from. Right now they are only images with no reference of origin.
> 
> should be documented in `images/licenses`. But no one did that **so I agree that it would be easier to import the non custom icons from an npm package** with an automated way to include only the used images in a release.

I like the current system. It's almost even faster cause you'll still go to whatever library we're gonna use website to check what icon you actually need.

I think it only makes sense to go for a library if we're obliged to specify license for every icon and can't get away with just "Google materials icons, some are modified".

**Comment by r10s** [comment]
some background:

- we are using comparable few icons (which is a good thing!), which are at least partly modified or even created from scratch. some icons also come from core. so, anyway, one would need often to copy .svg around 

- we take care, that icons between Android/iOS/Desktop are at least roughly the same, while still following system styles

- unless created from scratch, icons come from "material icon library", which is covered by the normal license, and do not require attribution - which is also fair, regarding the level of inventiveness for an arrow or a close button. i do not see the point of adding bureaucracy here

- on android/iOS, we indeed implicitly also use an icon library ("Material" and "SF Symbols") if possible and helpful. but we do not try to route things over there, if in doubt, we copy an .svg

so, all in all, this area is "hands on" but i do not see an issue with it :)

**Comment by r10s** [comment]
i suggest to close this issue, and next time, a standard icon is needed, try to pull it in from a library - one can then see if it makes sense.

i do not think a "refactoring" makes sense atm, there are more important things to do

**Comment by Simon-Laux** [comment]
I agree not enough value in starting yet another refactoring at this point. moving to project resurrection then.
