### ISSUE TITLE
Message details has overlapping text

### ISSUE THREAD

**Issue by maxphilippov** [deltachat/deltachat-desktop#4215]
Text in message details is overlapping

![Screenshot 2024-10-15 at 18 54 38](https://github.com/user-attachments/assets/d626a96b-e835-4a27-b259-73d69f6ed89b)

_Originally posted by @r10s in https://github.com/deltachat/deltachat-desktop/issues/3926#issuecomment-2414545145_

**Comment by Simon-Laux** [comment]
I suggest to go directly to improving this dialog with tabs as described in https://support.delta.chat/t/remade-message-details-and-show-them-in-a-friendly-matter-for-non-technical-users/2640/11

We have all apis we need.
[`backend.rpc.getMessageInfoObject`](https://js.jsonrpc.delta.chat/classes/RawClient.html#getMessageInfoObject) -> which returns a [`MessageInfo` Object](https://js.jsonrpc.delta.chat/types/T.MessageInfo.html)
read receipt ui was already implemented recently by @meganoahj and me.
So just some basic ui work and the question on whether or not to merge the reaction dialog into it (in an extra tab) .

**Comment by r10s** [comment]
let's leave reactions definetely out of that. reactions are more the "fun" and not "buerocratic".

but also the remainings are still vague.

in general, regarding maintainance, other bugs and ongoings, and keep things in a releasable state, i suggest to fix the issue at hand only. it is probably done within a few hours, not days. 

otherwise this will block releases
