### ISSUE TITLE
Make Arch/AUR package

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#426]

**Comment by Jikstra** [comment]
Investigated this a bit & this are the problems:
- libsasl from arch has another lib path, it's `/usr/lib/libsasl2.so` instead of `/usr/lib/libsasl2.so.2`
  - LD_PRELOADing electron doesn't work because the environment variable doesn't seem to get passed down to the node process
  - creating a soft link, which works but is hacky? I don't know too much abour AUR/ARCH pkgs. @The-Compiler maybe?
- electron-builder supports arch, so we could also build packages for arch. The problem is see is that deltachat-node won't be compatible if built on debian or any non arch os because of the wrong library name
- i tried patching the prebuilt .node file with `patchelf` but it corrupts the elf

Other ideas:
- is it possible to include libsasl into the deltachat-node prebuilds?

**Comment by The-Compiler** [comment]
My Arch system has `/usr/lib/libsasl2.so`, `/usr/lib/libsasl2.so.3` and `/usr/lib/libsasl2.so.3.0.0`. Symlinking that to `.so.2` would be a horrible idea (and probably wouldn't work), the whole point of the major version is that the two versions are incompatible.

Those are coming from libsasl 2.1.26 - is deltachat compatible with that at all?

**Comment by ralphtheninja** [comment]
> Those are coming from libsasl 2.1.26 - is deltachat compatible with that at all?

Afaik, yes.

cc @flub

**Comment by Jikstra** [comment]
@The-Compiler thanks for joining the discussion :)

@flub "normally" but not for arch, it's using libsasl2.so.3 even if the version number is 2.1.26-13. Maybe it's too new? However, the all included deltachat-core will probably solve this problem :)

**Comment by flub** [comment]
for e.g. `libsasl2.so.3.0.1` (and all it's symlinks): soname = `libsasl2.so.3`  The purpose of the `libsasl2.so` symlink is so that at build time this one is used (`-sasl2`), but at runtime the soname is used.

So you have a newer version of libsasl than the node extension was linked against.  sasl decided that a part of their ABI is not backwards compatible since libsasl bumped the soversion.  You need to either install `libsasl2.so.2` or re-build the node extension against your libsasl.

**Comment by ralphtheninja** [comment]
> i'm currently working on building a docker image which will build the deltachat-node stuff without dynamically linking to libsasl btw, and then this problem would go away (your first bullet point in other ideas essentially).

:heart: 

It would be nice if you could base it on this `Dockerimage` https://github.com/deltachat/docker-images/blob/master/debian-stretch-node-11/Dockerfile (or tweak the existing).

**Comment by The-Compiler** [comment]
Nitpicks:

- The PKGBUILD should have a `# Maintainer: Foo Bar <blah@example.com>` comment at the beginning
- No need to say `#branch=master` if it's the default branch.
- The separate `cp -r` lines could be one (`cp -r src1 src2 src3 target`)
- `deltachat-desktop.sh` should use `"$@"` instead of `$@` so arguments with spaces are quoted properly
- Maybe the wrapper script should go to `/usr/bin/deltachat` so you can also easily start it in a terminal?

Other than that, it looks fine, and installs/works. Takes 105 MB (not including dependencies such as Electron itself), but I guess that's to be expected.

**Comment by Jikstra** [comment]
@The-Compiler thanks a lot for your review, applied your nitpicks.
I guess we can reduce the install size quite a bit by removing all *.{c|h|ts|map|md} files.

**Comment by Jikstra** [comment]
It's done. https://aur.archlinux.org/packages/deltachat-desktop-git
