### ISSUE TITLE
Checkmark is gray and not green

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#450]
![screenshot from 2018-12-16 18-24-26](https://user-images.githubusercontent.com/308049/50056708-5c632380-0160-11e9-931c-1d317bcb6acb.png)

**Comment by Jikstra** [comment]
it's not delivered, we don't know such a thing as delivered, only read (delivered is only the css class we're using which is highly confusing :P). I guess the problem is that the other side isn't sending a read notification? Then this would be the same as https://github.com/deltachat/deltachat-desktop/issues/447

**Comment by ralphtheninja** [comment]
No it's not the same problem. The problem is that the check mark isn't green ;)

**Comment by Jikstra** [comment]
> No it's not the same problem. The problem is that the check mark isn't green ;)

Haha :D Reading is hard, understanding it even harder ^^
