### ISSUE TITLE
Media view: Some video files shown in Documents

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#469]
`.webm` movie is shown in `Documents` and not in `Video`

![screenshot from 2018-12-20 23-59-13](https://user-images.githubusercontent.com/308049/50315546-80519c80-04b3-11e9-927e-c7d5027adac0.png)

**Comment by karissa** [comment]
Do you know if the video was sent with desktop or android-dev? The way the file is classified is based on how it is sent, the `type` is sent from the sender. Core tries to make a good guess about it, though

**Comment by ralphtheninja** [comment]
It was sent from desktop.

**Comment by nicodh** [comment]
still exists in current master...

**Comment by karissa** [comment]
Probably I would guess because desktop doesn't do a good enough job at sending the right type to core

**Comment by link2xt** [comment]
I have tried sending a [sample WebM from Wikipedia](https://upload.wikimedia.org/wikipedia/commons/8/87/Schlossbergbahn.webm) to myself using the latest DeltaChat Desktop (commit cd2217d385d7f902deb90a9009a9aa45efa47024). Then I saved email to `.eml` file and decrypted it with `gpg -d email.eml`. The attachement is `Content-Type: application/octet-stream; name="Schlossbergbahn.webm"`. So the bug is indeed in the Desktop, it does not set the MIME type correctly.

**Comment by link2xt** [comment]
DeltaChat Desktop does not set the optional mime argument of [`setFile` method](https://github.com/deltachat/deltachat-node#msgsetfilefile-mime):
https://github.com/deltachat/deltachat-desktop/blob/b9a5cf2d26200fc7195a204c2ec2f299a0c73c12/src/main/deltachat/messagelist.js#L9

`deltachat-core-rust` then tries to guess MIME type based on extension, but it only recognizes `.png`, `.jpg`, `.jpeg`, `.jpe` and `.gif`:
https://github.com/deltachat/deltachat-core-rust/blob/8a0fc609e6c1aa61947ee9fa965d87b104b6a716/src/dc_mimefactory.rs#L1209-L1226

The solution is probably to add proper MIME type support to DeltaChat Desktop and manually set the second argument of `setFile`, because there are cases when file extension may be incorrect or unavailable, for example if the file is pasted from the clipboard.

**Comment by pabzm** [comment]
Could someone check if this still is broken?

**Comment by link2xt** [comment]
@pabzm Just tried, sent the same Webm from wikipedia to myself, it goes into documents.

**Comment by link2xt** [comment]
I have opened https://github.com/deltachat/deltachat-core-rust/pull/1142 as a workaround

**Comment by r10s** [comment]
ftr, in upcoming core, webm will be sent as file again, same as for other types. see https://github.com/chatmail/core/pull/7381 for reasoning.

this issue gets a "won't fix" for now
