### ISSUE TITLE
Voice/Audio messages

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#484]

**Comment by nicodh** [comment]
Since we plan to implement this feature anyway we don't need an issue for that...

**Comment by Simon-Laux** [comment]
I disagree:  This is rather an "Thats missing in comparison with the android app" Feature

**Comment by muelli** [comment]
what's the rationale for closing this?

**Comment by Jikstra** [comment]
@muelli we're trying to only track bugs in the issue tracker.

**Comment by muelli** [comment]
okay. cool.
But is the lack of feature parity not a bug?

**Comment by Jikstra** [comment]
We have a lot of lacking feature parity, keeping all of it in the issue tracker is too much. Our idea is to only keep feature issues on which we are currently working to not have many dead issues. As a developer we easily loose track of what's important and what's not.

**Comment by EchedeyLR** [comment]
Could you link the forum discussion here too of there is any or create one for following updates easily?

**Comment by r10s** [comment]
forum feature proposals go to https://support.delta.chat/c/features/6 - if there is no entry that matches, feel free to create one.

**Comment by EchedeyLR** [comment]
For personal issues, I am not using the forum since some months ago. This is why I asked if you could create one in the case there was not an existing entry.

**Comment by r10s** [comment]
> However, I have no issues to check 

i think, if it comes to implementation, this issue will be re-opened, it is in the [Resurrection project](https://github.com/orgs/deltachat/projects/19), so it is not totally dead :)

i also think, at _some point_, audio/video recording will be implemented for desktop, it is useful, no doubt.

however, _currently_, with the few resources we have, there are _far_ more important things to do. this may also be the reason, that this issue is not yet re-filed in forum - where tons of others are :)
