### ISSUE TITLE
existing chats not displayed

### ISSUE THREAD

**Issue by muelli** [deltachat/deltachat-desktop#494]
- Platform (linux/mac/windows):
linux

- Delta Chat Desktop Version:
0.97.0.

- Expected behavior:

see all the chats from the mobile client

- Actual behavior:

I can only see new chats

- Steps to reproduce the problem:

maintain an account with the Android app, have a few chats.
Enter same credentials on desktop version.
See no existing chat.

- Screenshots:
- Logs:

**Comment by ralphtheninja** [comment]
Chats are only stored on the local device. You could try export/import.

**Comment by muelli** [comment]
are you referring to the desktop client?
Because I see many messages in my IMAP folder. The mobile version does not seem to delete the messages.
The desktop client could pick the existing messages up.

**Comment by Simon-Laux** [comment]
anyways that is probably also an core issue

**Comment by Jikstra** [comment]
@muelli i like the feature idea, sadly we can't do anything about this on desktop. I opened a core issue for this: https://github.com/deltachat/deltachat-core/issues/493
Feel free to further contribute there about this issue.

**Comment by muelli** [comment]
what is the story for multiple delta.chat installations, e.g. two android apps with the same credentials, two desktop installations, or one android and a desktop installation?
Is that use-case not supported?

**Comment by Simon-Laux** [comment]
It is supported, but currently you have to import the backup(your chat history) manually. Am 30.12.2018 18:46 schrieb muelli <notifications@github.com>:what is the story for multiple delta.chat installations, e.g. two android apps with the same credentials, two desktop installations, or one android and a desktop installation?
Is that use-case not supported?

**Comment by baptx** [comment]
@Jikstra The issue "Retrieve old chats over imap on first login" you created will not receive any updates anymore since the repository was archived.
You or someone else should create the issue again on the new repository https://github.com/deltachat/deltachat-core-rust since it was not imported automatically.
I wanted to add a comment about it also. If the feature is added, old chats should only be added when clicking on the "+" button to add a chat (or there should be an option to allow this). Otherwise, we will have a lot of unwanted chats, for example newsletters or work emails that have nothing to do in a chat app.

**Comment by baptx** [comment]
@Simon-Laux There is already a feature request for it on the forum that I mentioned in my message so I don't think it is necessary to create another one. I added a comment there also and noticed the workaround does not work for restoring old reactions to messages.
