### ISSUE TITLE
Open context menu on right click on message instead of showing the three dot menu

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#672]
Additional thing would be to move the download attachment button also into the context menu.

@nicodh even if your changes already highly improve the situation, this might make it even better and introduces a general ui/ux element which we can also use for the chat list items and don't need to show/hide something on hover.

**Comment by nicodh** [comment]
It's already there, but restricted to small screens by css: 
https://github.com/deltachat/deltachat-desktop/blob/26e1f4dc18f7fd1f7bfdc5dca35c46a11cca7940/css/conversations/_modules.scss#L2366

For small screen width it is hidden in the message bubble but visible in the context menu.
Not sure who implemented that, since git blame shows only a merge commit...

**Comment by Jikstra** [comment]
> For small screen width it is hidden in the message bubble but visible in the context menu.
Not sure who implemented that, since git blame shows only a merge commit...

All scss/js which is in in a conversations folder is originally from the signal desktop code. So signal implemented this.

**Comment by violoncelloCH** [comment]
as already stated in https://github.com/deltachat/deltachat-desktop/pull/666#issuecomment-461214159 I would not completely remove the three dot menu, but only introduce it as an additional way to access context menus
