### ISSUE TITLE
mark noticed chats

### ISSUE THREAD

**Issue by karissa** [deltachat/deltachat-desktop#88]

**Comment by r10s** [comment]
it's related, but it it is not the same.

- if a chat is opened (clicked in the chatlist), for this chat `dc_marknoticed_chat()` should be called.
this results in all messages of the chat being no longer _fresh_ and dc_get_fresh_msg_cnt() will return 0 for this chat (unless new messages arrive in between).
the sender of the messages is not informed about this action.
- in addition  to this, if a _single message_ is shown on the screen so that it is visible in a way to the user dc_markseen_msg() should be called for this single messages.
this results in a read receipt send back to the sender (if enabled, however) and in changing the state on the IMAP-server
