### ISSUE TITLE
Can't login with Nauta account

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#909]
Automatic configuration in delta-desktop doesn't work for Nauta accounts, so I try to set configuration manually but also fails to login (see screenshot)
(automatic and manual configuration works in deltachat-android)

- Platform (linux/mac/windows): GNU/Linux
- Delta Chat Desktop Version: 0.105.0-pre2-PREVIEW
- Logs: the logs linked in the app seems to be pretty useless
- Screenshots:
![Screenshot_2019-07-25_17-50-59](https://user-images.githubusercontent.com/24558636/61911664-23fda200-af06-11e9-8159-8292be8adcfc.png)

**Comment by Jikstra** [comment]
For whatever reason it tries to connect with ssl/tls and ignores your disabling of secure connections. And it fails because of the self signed certificate. It could be either we're passing the configuration wrongly to core, or the rust core has a bug with accepting configurations on the configure progress. Thanks for reporting, 0.105.0+ is still quite buggy because of the new rust core and many moving targets. Probably stay with 0.104.0 for a more stable version.

**Comment by Jikstra** [comment]
Closing this because it's very likely a core bug/feature request of accepting self signed certificates.
