### ISSUE TITLE
Fix integration tests

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#961]
- Currently they do basic dom checking but the wait 500ms before checking if the dom element is there. That's a ugly hack and fails often in ci
  - Solution: use enzyme? https://github.com/airbnb/enzyme
- The integration tests are run against the dev build. So having a dependency flagged as dev dependency but it's needed in the production build won't make the integration tests fail. That's bad.

@nicodh

**Comment by nicodh** [comment]
As long as we run integration tests in Electron we depend on [Spectron](https://electronjs.org/spectron) for integration tests which is a Selenium adapter for electron. I really don't like the Selenium DOM Api, it produces a lot of "random" results, but I don't know what else to use. We can write more unit/component tests and mock everything else, but that's another scope then.
So far I see only one explicit wait when trying to connect with invalid data waiting for the failure message (which is fine, since the core retries several times) and another one when checking for persisted settings (which is fine too since settings are persisted in a SAVE_DEBOUNCE_INTERVAL delay. But in general I agree, these tests are far too instable...

**Comment by Simon-Laux** [comment]
Another thing is that it checks for hard coded translations instead of using the translations

**Comment by pabzm** [comment]
This appears to have stalled. If someone is working on it, please re-open.
